<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->render('_templates/css.phtml'); ?>
    </head>
    <body>
        <div id="mt_email">
            <?php echo $this->render('_templates/header.phtml'); ?>

            <div id="mt_email_content">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <p>An FTP account for your development store on magetesting.com has been created.</p>

                    <p>Connection details:</p>

                    <p>
                        host: <?php echo $this->ftphost ?>
                        <br />Your store FTP login: <?php echo $this->ftpuser ?>
                        <br />Your store FTP password: <?php echo $this->ftppass ?>
                    </p>

                    <?php echo $this->render('_templates/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>