<?php echo $this->render('_emails/_templates/email_top.phtml'); ?>

    <p>An FTP account for your development store on magetesting.com has been created.</p>

    <p>Connection details:</p>

    <p>
        host: <?php echo $this->ftphost ?>
        <br />Your store FTP login: <?php echo $this->ftpuser ?>
        <br />Your store FTP password: <?php echo $this->ftppass ?>
    </p>

<?php echo $this->render('_emails/_templates/email_bottom.phtml'); ?>