<?php echo $this->render('_emails/_templates/email_top.phtml'); ?>
    <p>A MySQL account for your development store on magetesting.com has been created.</p>

    <p>Please visit <?php echo $this->dbhost ?> for a web based tool to manage your database.</p>

    <p> 
        <br />Your store database login: <?php echo $this->dbuser ?>
        <br />Your store database password: <?php echo $this->dbpass ?>
    </p>

<?php echo $this->render('_emails/_templates/email_bottom.phtml'); ?>