<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->render('_templates/css.phtml'); ?>
    </head>
    <body>
        <div id="mt_email">
            <?php echo $this->render('_templates/header.phtml'); ?>

            <div id="mt_email_content">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <p>A MySQL account for your development store on magetesting.com has been created.</p>

                    <p>Please visit <?php echo $this->dbhost ?> for a web based tool to manage your database.</p>

                    <p> 
                        <br />Your store database login: <?php echo $this->dbuser ?>
                        <br />Your store database password: <?php echo $this->dbpass ?>
                    </p>

                    <?php echo $this->render('_templates/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>