<p>
    <b>Your accounts on Magetesting.com has been created!</b>
</p>

<p>FTP:</p>
<p>
    host: <?php echo $this->ftphost ?>
    <br />username: <?php echo $this->ftpuser ?>
    <br />password: <?php echo $this->ftppass ?>
</p>

<p>MYSQL:</p>
<p>
    host: <?php echo $this->dbhost ?>
    <br />username: <?php echo $this->dbuser ?>
    <br />password: <?php echo $this->dbpass ?>
</p>

<p>
    -- <br /> <a href="<?php echo $this->storeUrl ?>">Magetesting.com</a>
</p>
