<?php echo $this->render('_emails/_templates/css.phtml'); ?>

<div id="mt_email">
    <?php echo $this->render('_emails/_templates/header.phtml'); ?>

    <div id="mt_email_content">
        <p><span class="greeting">Hi,</span><br>Your password has been reset.</p>
        <p>Please click this link to set your new password:</p> 
        <p><a href="<?php echo $this->resetLink; ?>"><?php echo $this->resetLink; ?></a></p>
        <p>The username we have on file for this email address is: <?php echo $this->login; ?></p>

        <?php echo $this->render('_emails/_templates/footer.phtml'); ?>
    </div>
</div>