<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->render('_emails/_templates/css.phtml'); ?>
    </head>
    <body>
        <div id="mt_email">
            <?php echo $this->render('_emails/_templates/header.phtml'); ?>

            <div id="mt_email_content">
                <div class="box">
                    <div class="tab-stripe"></div>
					<p><span class="greeting">Hi,</span><br>Thanks for registering with Mage Testing!</p>

					<p>Please click this link to confirm your registration so you can start setting up your site:</p>

					<p><a href="<?php echo $this->activationLink; ?>"><?php echo $this->activationLink; ?></a></p>

					<?php echo $this->render('_emails/_templates/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>