<?php echo $this->render('_emails/_templates/email_top.phtml'); ?>
    <p><span class="greeting" style="color: #F64135; font-size: 24px; font-weight: bold;">Hi,</span></p>
    <p>Thanks for registering with Mage Testing!</p>

    <p>Please click this link to confirm your registration so you can start setting up your site:</p>

    <p><a href="<?php echo $this->activationLink; ?>"><?php echo $this->activationLink; ?></a></p>

<?php echo $this->render('_emails/_templates/email_bottom.phtml'); ?>