<?php echo $this->render('_emails/_templates/email_top.phtml'); ?>

    <p><span class="greeting">Hi,</span></p>
    <p>Your password has been reset.</p>
    <p>Please click this link to set your new password:</p> 
    <p><a href="<?php echo $this->resetLink; ?>"><?php echo $this->resetLink; ?></a></p>
    <p>The username we have on file for this email address is: <?php echo $this->login; ?></p>

<?php echo $this->render('_emails/_templates/email_bottom.phtml'); ?>