<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-03 at 10:41:33.
 */
class Application_Model_UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application_Model_User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application_Model_User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testUserModel() {
        $this->assertType('Application_Model_User', $this->object);
    }

    /**
     * @covers Application_Model_User::save
     * @todo   Implement testSave().
     */
    public function testSave() {

    }


}
