<style type="text/css" media="screen">
  #mt_email {
    margin: 0;
    padding: 0;
    font-family: Helvetica, Arial, san-sarif;
  }
  #mt_email_header {
    margin: 0;
    padding: 0;
    height: 60px;
  }
  #mt_email_header div.line {
    min-height: 5px;
    background: none repeat scroll 0 0 #F64135;
  }
  #mt_email_header div.logo {
    margin: 20px 40px;
  }
  #mt_email_content {
    margin: 0 20px;
    padding: 20px;
    font-size: 12px;
    background: none repeat scroll 0 0 #FFFFFF;
  }
  #mt_email_content p {
    margin-bottom: 20px;
    padding: 0 20px;
  }
  #mt_email_content p .greeting {
    color: #F64135;
    font-size: 24px;
    font-weight: bold;
  }
  #mt_email_content div.box {
    border: 1px solid #E5E5E5;
    border-radius: 6px 6px 6px 6px;
    box-shadow: 0 8px 6px -6px #888888;
    margin-bottom: 20px;
    margin-top: 10px;
  }
  #mt_email_content .tab-stripe {
      background: none repeat scroll 0 0 #34AAE5;
      float: left;
      min-height: 60px;
      min-width: 5px;
      border-top-left-radius: 6px;
  }
  #mt_email_footer p a {
    color: #F64135;
    text-decoration: underline;
  }
</style>