<style type="text/css" media="screen">
  #mt_email {
    margin: 0;
    padding: 0;
    font-family: Helvetica, Arial, san-sarif;
  }
  #mt_email_header {
    margin: 0;
    padding: 0;
    height: 100px;
  }
  #mt_email_header div.line {
    min-height: 5px;
    background: none repeat scroll 0 0 #F64135;
  }
  #mt_email_header div.logo {
    margin: 20px;
  }
  #mt_email_content {
    padding: 20px;
    font-size: 12px;
    background: none repeat scroll 0 0 #F1F1F1;
    -webkit-border-radius: 6px;
    -moz-border-radius: 6px;
    -o-border-radius: 6px;
    border-radius: 6px;
  }
  #mt_email_content p {
    margin-bottom: 20px;
  }
  #mt_email_content p .greeting {
    color: #F64135;
    font-size: 24px;
    font-weight: bold;
  }

  #mt_email_footer p a {
    color: #F64135;
    text-decoration: underline;
  }
</style>