<!DOCTYPE html>
<html lang="en">
    <head><meta charset="utf-8"></head>
    <body>
        <div id="mt_email" style="margin: 0; padding: 0; font-family: Helvetica, Arial, san-sarif;">
            
            <div id="mt_email_header" style="margin: 0; padding: 0; height: 60px;">
                <div class="logo" style="margin: 20px 40px;"><img src="http://magetesting.com/public/img/logo_magetesting.jpg" alt="Mage Testing"></div>
            </div>

            <div id="mt_email_content" style="margin: 0 20px; padding: 20px; font-size: 12px; background: none repeat scroll 0 0 #FFFFFF;">
                <div class="box" style="border: 1px solid #E5E5E5; border-radius: 6px 6px 6px 6px; box-shadow: 0 8px 6px -6px #888888; margin-bottom: 20px; margin-top: 10px;">
                    <div class="tab-stripe" style="background: none repeat scroll 0 0 #34AAE5; float: left; min-height: 60px; min-width: 5px; border-top-left-radius: 6px;"></div>