<div id="ext-m">
  <div id="ext-l">
    <?php if($this->logo): ?>
        <?php echo $this->thumbnail($this->logo, 150, null, array(), $this->imagePath($this->logo, 'extension/logo', false, false)); ?>
    <?php endif; ?>
      
  </div>

  <div id="ext-r">
      <h3 style="display: inline;">Additional Stores: <?php echo $this->additional_stores; ?>
        <h4 class="ext-price">Price: $<?php echo $this->price; ?></h4>

        <h5>Notes:</h5>
        <p>Final price is calculated as follows: (Store Quantity * Store Price) * (Days until plan expiration/ Plan full period)</p>
        
  </div>
</div>