<div id="ext-m">
  <div id="ext-l">
    <?php if($this->logo): ?>
        <?php echo $this->thumbnail($this->logo, 150, null, array(), $this->imagePath($this->logo, 'extension/logo', false, false)); ?>
    <?php endif; ?>
      
  </div>

  <div id="ext-r">
      <h3 style="display: inline;">Additional Stores: <?php echo $this->additional_stores; ?>
        <h4 class="ext-price">Price: $<?php printf("%d", (float)$this->store_price*100*(int)$this->additional_stores/100); ?></h4>

        <?php if($this->description): ?>
            <h5>Description:</h5>
            <p><?php echo $this->description; ?></p>
        <?php endif; ?>
        
  </div>
</div>