<div class="row">
    <div class="span12">
        <div class="form-box">
            <div class="box">
                <form class="form-stacked" id="payment-form" method="POST" action="<?php echo $this->url(array('controller' => 'payment', 'action' => 'change-plan'), 'default', true); ?>">
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                    <input type="hidden" name="confirm" value="1" />
                    <div class="tab-stripe tab-stripe-red"></div>
                    <fieldset>
                        <legend>Note</legend>
                        <p>
                            You have used your "<?php echo $this->plan_change_calculation['plan_name']; ?>" plan for <?php echo $this->plan_change_calculation['used_days']; ?> days from <?php echo $this->plan_change_calculation['billing_period']; ?> available.
                            <?php if(0.0 !== $this->plan_change_calculation['amount']): ?>
                            To change plan to "<?php echo $this->new_plan_name; ?>" we will need to
                            <?php if($this->plan_change_calculation['amount'] > 0): ?>bill<?php else: ?>refund<?php endif;?>
                            you for <?php echo $this->plan_change_calculation['amount']; ?>$ and plan will be active to <?php echo date('F jS, Y', $this->plan_change_calculation['new_plan_end']); ?>.
                            <?php else: ?>
                            Changed plan will be active to <?php echo date('F jS, Y', $this->plan_change_calculation['new_plan_end']); ?>.
                            <?php endif; ?>
                        </p>
                    </fieldset>
                    <div class="tab-stripe tab-stripe-red"></div>
                    <fieldset>
                        <legend>Payment Details</legend>
                        <?php echo $this->specific_content; ?>
                    </fieldset>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-inverse pull-right">
                            <i class="icon-white icon-ok"></i>&nbsp;Pay
                        </button>
                    <?php if(!$this->show_billing_and_card): ?>
                        <p class="pull-right braintree-vault-note">
                            Your Credit Card saved in the secure Braintree Payment Gateway Vault will be used for payment.
                        </p>
                    <?php endif; ?>

                        <a href="<?php
                        switch($this->source){
                            case 'extension':
                                echo $this->url(array('controller' => 'queue', 'action' => 'extensions','store'=> $this->domain), 'default', true);
                                break;
                            case 'deployment-request':
                                echo $this->url(array('controller' => 'user', 'action' => 'dashboard'), 'default', true);
                                break;
                            case 'plan':
                            default:
                                echo $this->url(array('controller' => 'my-account', 'action' => 'compare'), 'default', true); 
                                break;
                        }
                        ?>" class="btn">Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>