<div id="ext-m">
      <div id="ext-l">
        <?php if($this->logo): ?>
            <?php echo $this->thumbnail($this->logo, 150, null, array(), $this->imagePath($this->logo, 'extension/logo', false, false)); ?>
        <?php endif; ?>
          
      </div>

      <div id="ext-r">
          <h3 style="display: inline;"><?php echo $this->name; ?></h3> by <?php echo $this->author; ?>
            <h4 class="ext-price">Price: $<?php printf("%d", $this->price); ?></h4>

            <?php if($this->description): ?>
                <h5>Description:</h5>
                <p><?php echo $this->description; ?></p>
            <?php endif; ?>
            
      </div>
</div>



