<p style="margin-bottom: 20px; padding: 0 20px;"><b>User 
<?php
$url = $this->serverUrl . '/user/detail/id/' . $this->user->getId();
?>
'<a href="<?php echo $url; ?>"><?php echo $this->user->getLogin(); ?></a>'
 bought extension 
<?php
$url = $this->serverUrl . '/extension/edit/id/' . $this->extension->getId();
?>
'<a href="<?php echo $url; ?>"><?php echo $this->extension->getName(); ?></a>'
 for $<?php echo $this->extension->getPrice(); ?>.</b></p>