<p style="margin-bottom: 20px; padding: 0 20px;"><b>User 
<?php
$url = $this->serverUrl . '/user/detail/id/' . $this->user->getId();
?>
'<a href="<?php echo $url; ?>"><?php echo $this->user->getLogin(); ?></a>'
 changed plan to '<?php echo $this->plan->getName(); ?>'.
</b></p>
<?php
$operation =
    $this->amount < 0
        ? 'refunded $' . ($this->amount * -1)
        : 'charged $' . $this->amount;
?>
<p>Operation: <?php echo $operation;?></p>