<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->render('_templates/css.phtml'); ?>
    </head>
    <body>
        <div id="mt_email">
            <?php echo $this->render('_templates/header.phtml'); ?>

            <div id="mt_email_content">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <p><span class="greeting">Hello</span></p>
                    <?php echo $this->content; ?>
                    <?php echo $this->render('_templates/footer.phtml'); ?>
                </div>
            </div>
        </div>
    </body>
</html>