<p style="margin-bottom: 20px; padding: 0 20px;"><b>New user with username 
<?php
$url = $this->serverUrl . '/user/detail/id/' . $this->user->getId();
?>
'<a href="<?php echo $url; ?>"><?php echo $this->user->getLogin(); ?></a>'
 has just registered.</b></p>

<?php if($this->preselected_plan): ?>
<p style="margin-bottom: 20px; padding: 0 20px;">Preselected plan: <?php echo $this->preselected_plan; ?></p>
<?php endif; ?>
<?php if($this->used_coupon): ?>
<p style="margin-bottom: 20px; padding: 0 20px;">Used coupon: <?php echo $this->used_coupon; ?></p>
<?php endif; ?>
<?php if($this->free_trial): ?>
<p style="margin-bottom: 20px; padding: 0 20px;">User has requested free trial</p>
<?php endif; ?>