<h3>User New user with username 
<?php
$url = $this->serverUrl . '/user/detail/id/' . $this->user->getId();
?>
'<a href="<?php echo $url; ?>"><?php echo $this->user->getLogin(); ?></a>'
 has just registered.</h3>

<?php if($this->preselected_plan): ?>
<br />
Preselected plan: <?php echo $this->preselected_plan; ?>
<?php endif; ?>
<?php if($this->used_coupon): ?>
<br />
Used coupon: <?php echo $this->used_coupon; ?>
<?php endif; ?>