<div class="row">
    <div class="span12">
        <h1>About Us</h1>

        <div class="row">
            <div class="span8">
                <p>Mage Testing is a service to quickly build Magento demo stores and install multiple extensions with one click. We started to build this tool after we released a couple Magento extensions and began realizing that the large majority of Magento store owners did not have a development website and were testing out new features on their live website. We’ve heard from store owners that installing multiple extensions from various developers were causing their stores to crash and often times closing their business until the issue was fixed. As seasoned developers, we know that developing without a separate development website will consistently lead to disaster.</p>
                <p>The process of exploring Magento extensions is cumbersome for merchants and developers alike. We’ve created a tool that helps fix this issue quickly and efficiently.</p>
                <p>We’ve been sharing ideas with the Magento community for months and are pleased to see the excitement as this Magento service comes to market.</p>
                <p>It’s our hope that Mage Testing can be used to develop Magento as it’s intended to be developed and that all store owners can experience the extreme speed, flexibility and reliability that Magento was designed for.</p>
            </div>
            <div class="span4 image-column">
                <img class="pull-right" src="<?php echo $this->baseUrl('/public/img/magento_developers_badge.png'); ?>" alt="" />
                <img class="pull-right" src="<?php echo $this->baseUrl('/public/img/magento_badge.jpg'); ?>" alt="" />
            </div>
        </div>
    </div>
</div>

<?php
$data = <<<EOT

EOT;
echo $this->partial('_partials/helpContext.phtml', array('data' => $data));
?>