<div class="row">
    <div class="span12">
        <h1>Contact the Mage Testing Team</h1>
        <div class="form-box">
            <div class="box">
                <form method="<?php echo $this->form->getMethod() ?>">
                    <div class="tab-stripe"></div>
                    <fieldset>
                        <legend>Contact Details</legend>
                        <div class="row">
                            <div class="span4">
                                <div class="control-group"><label class="control-label required" for="sender_name">Your Name</label>
                                    <div class="controls">
                                        <?php echo $this->form->getElement('sender_name') ?>
                                    </div>
                                </div>
                           </div>
                           <div class="span4">
                               <div class="control-group"><label class="control-label required" for="sender_email">Your Email Address</label>
                                    <div class="controls">
                                        <?php echo $this->form->getElement('sender_email') ?>
                                    </div>
                                </div>
                           </div>
                       </div>

                        <div class="row">
                            <div class="span8">
                                <div class="control-group"><label class="control-label required" for="subject">Subject</label>
                                    <div class="controls">
                                        <?php echo $this->form->getElement('subject') ?>
                                    </div>
                                </div>
                           </div>
                        </div>
                        <div class="row">
                            <div class="span8">
                                <div class="control-group"><label class="control-label required" for="message">Message</label>
                                    <div class="controls">
                                        <?php echo $this->form->getElement('message') ?>
                                    </div>
                                </div>
                           </div>
                        </div>
                    </fieldset>

                    <div class="form-actions">
                        <button type="submit" name="send" id="" class="btn btn-inverse pull-right"><i class="icon-white icon-ok"></i> Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php
$data = <<<EOT

EOT;
echo $this->partial('_partials/helpContext.phtml', array('data' => $data));
?>