<div class="row">
    <div class="span12">
        <h1>Contact Us</h1>
        <div class="form-box">
            <div class="box">
                <form
                    enctype="<?php //echo $this->form->getEnctype() ?>"
                    method="<?php //echo $this->form->getMethod() ?>"
                    class="<?php //echo $this->form->getAttrib('class') ?>">

                    <div class="tab-stripe"></div>
                    <fieldset>
                        <legend>Message details</legend>
                        <div class="row">
                            <div class="span4">
                                <div class="control-group"><label class="control-label required" for="sender_name">Your name</label>
                                    <div class="controls">
                                        <input class="span4" type="text" value="" id="" name="sender_name">
                                    </div>
                                </div>
                           </div>
                           <div class="span4">
                               <div class="control-group"><label class="control-label required" for="sender_email">Your email address</label>
                                    <div class="controls">
                                        <input class="span4" type="text" value="" id="" name="sender_email">
                                    </div>
                                </div>
                           </div>
                       </div>

                        <div class="row">
                            <div class="span8">
                                <div class="control-group"><label class="control-label required" for="subject">Subject</label>
                                    <div class="controls">
                                        <input class="span8" type="text" value="" id="" name="subject">
                                    </div>
                                </div>
                           </div>
                        </div>
                        <div class="row">
                            <div class="span8">
                                <div class="control-group"><label class="control-label required" for="message">Message</label>
                                    <div class="controls">
                                        <textarea class="span8" rows="5"></textarea>
                                    </div>
                                </div>
                           </div>
                        </div>
                    </fieldset>

                    <div class="form-actions">
                        <button type="submit" name="send" id="" class="btn btn-inverse pull-right"><i class="icon-white icon-ok"></i> Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>