    <h1>Your Sandbox</h1>

    <p><a href="#" class="btn primary large">New Build</a></p>

    <table class="bordered-table">
      <thead>
        <tr>
          <th>Edition</th>
          <th>Version</th>
          <th>Status</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>CE</td>
          <td>1.3.2.4</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.3.3.0</td>
          <td><span class="label warning">In Queue</span> <span class="label">15 minutes left</span></td>
          <td><a href="#" class="btn danger disabled">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.4.1.1</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.4.2.0</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.5.1.0</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.6.0.0</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
        <tr>
          <td>CE</td>
          <td>1.6.1.1</td>
          <td><span class="label success">Ready</span></td>
          <td><a href="#" class="btn danger">Close</a></td>
        </tr>
      </tbody>
    </table>