<div class="row">
    <div class="span12">
        <h1>Partners</h1>

        <div class="row partner">
        	<div class="span8">
        		<h4>Rocket Web</h4>
        		<p>Our core business is developing easy to use, efficient Magento stores. Rocket Web also develops free and premium Magento extensions. All of our extensions are available for exploration, testing and purchase with Mage Testing. We’re excited to be using our extensions in Mage Testing as it helps us to discover and resolve any bugs.</p>
        	</div>
            <div class="span3 pull-right partner-logo">
        		<img src="<?php echo $this->baseUrl('/public/img/rocketweb-logo.gif'); ?>" alt="" />
            </div>
        </div>
        <div class="row partner">
        	<div class="span8">
        		<h4>aheadWorks</h4>
        		<p>We have been using aheadWorks extensions for years. Nearly every customer site we have built has at least one aheadWorks extension. We are proud to be able to offer the Magento community the ability to evaluate, purchase and deploy aheadWorks extensions.</p>
        	</div>
        	<div class="span3 pull-right partner-logo">
                <img src="<?php echo $this->baseUrl('/public/img/aheadworks-logo.gif'); ?>" alt="" />
            </div>
        </div>
        <div class="row partner">
        	<div class="span8">
        		<h4>papertrail</h4>
        		<p>We use Mage Testing to help us see if new website features are broken before implementing on a live site. We use papertrail to help us understand why the new features are broken. Magento generates excellent log and debugging information in several different files. Web servers have additional files with relevant log information. papertrail brings all these files into one easy to use, filterable web based interface.</p>
        	</div>
        	<div class="span3 pull-right partner-logo">
                <img src="<?php echo $this->baseUrl('/public/img/papertrail-logo.png'); ?>" alt="" />
            </div>
        </div>
        <div class="row partner">
        	<div class="span8">
        		<h4>Magento Connect</h4>
        		<p>Mage Testing includes many free extensions from Magento Connect. Often times these are the most important extensions to test as many will not include support. We see Mage Testing as a critical extension of Magento Connect.</p>
        	</div>
        	<div class="span3 pull-right partner-logo">
                <img class="" src="<?php echo $this->baseUrl('/public/img/magento-connect.gif'); ?>" alt="" />
            </div>
        </div>
    </div>
</div>