<?php $span = 'span8'; ?>

<div class="row">
    <div class="span12">
        <h1>Privacy Policy</h1>

        <div class="form-box">
            <div class="box">
                <div class="tab-stripe"></div>
                <fieldset>
                    <div class="row" style="margin-top: 20px;">
                        <div class="<?php echo $span; ?>">
                            <p>This Privacy Policy describes the types of information MageTesting.com ("we", "us", "the Service") collects and how we use that information. If You do not agree to the terms of this Privacy Policy, please do not use MageTesting.com and do not access the MageTesting.com website located at http://magetesting.com ("the Site").</p>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Information We Collect</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>If You choose to use the Service, we may require you to provide contact and identity information, billing information, and other personal information as indicated on the Site. Once you register on the Site, You are no longer anonymous to us. We collect and store the following information:</p>
                            <ul>
                                <li>Email address, physical contact information, and financial information;</li>
                                <li>Computer sign-on data, statistics on page views, traffic to and from the Site and ad data (all through cookies - You can take steps to disable cookies on your browser, however this is likely to affect your ability to use the Service);</li>
                                <li>Remote access codes to your server if you choose to host a copy of your website using the Service.</li>
                                <li>Credit Card information can only be used for recurring billing and extension purchases and is stored in the encrypted PCI Compliant, PA-DSS certified Braintree Payment Solutions service and is never readable to any MageTesting.com employee.</li>
                                <li>As you may use the Service as your Magento development website, any information you save in the Magento administrator is stored using Magento's standard security procedures on a MageTesting.com server.</li>
                            </ul>
                            <p>We take privacy seriously and hold any information for your benefit in using the Service. We will gladly, completely remove any account from our system in a prompt manner by submitting a support request to do so. Confirmation via phone or email may be required so as to not unintentionally remove an account.</p>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Our Use of Your Information</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>We use your personal information to:</p>
                            <ul>
                            	<li>provide Products and Services;</li>
                            	<li>resolve disputes, calculate and collect fees, and troubleshoot problems;</li>
                            	<li>customize users' experience, analyze site usage, improve and measure interest in our services, and inform users about services and updates;</li>
                            	<li>communicate administrative announcements when we need to provide users with information that may affect their use of Products or Services;</li>
                            	<li>communicate marketing and promotional offers to our users;</li>
                            	<li>provide customer service; and</li>
                            	<li>perform other business activities as described when we collect the information.</li>
                            </ul>
                            <p>As part of your registration for Products or Services on the Site, you agree that you may receive certain administrative communications from us, such as administrative announcements and customer service messages regarding Products or Services and products during the period that we provide Products or Services to you, and you will not be able to opt out of receiving such administrative communications.</p>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Our Disclosure of Your Information</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>We do not sell or rent your personal information to third parties for their marketing purposes. We may disclose personal information to respond to legal requirements, enforce our policies, respond to claims that a listing or other content violates other's rights, or protect anyone's rights, property, or safety. We may also share personal information with:</p>
                            <ul>
                            	<li>service providers who help with our business operations and assist in the delivery of Products or Services to our users. These service providers are under confidentiality agreements with us;</li>
                            	<li>law enforcement or other government officials in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, violations of law, or as otherwise required by law</li>
                            </ul>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Accessing, Reviewing and Changing Your Personal Information</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>If you are registered to receive Products or Services, you can access, review and modify your personal information at any time by logging into your My Account page located at https://secure.qtmsoft.com We delete personal information when we no longer need it for the purposes we described earlier. We retain personal information as permitted by law to resolve disputes, enforce our policies, and help prevent bad guys from coming back.</p>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Security</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>To prevent unauthorized access, promote data security, and encourage appropriate use of information, we use a variety of tools (encryption technologies, passwords, physical and electronic security, procedural safeguards) to assist in the protection of Your information. However, "perfect security" does not exist on the Internet, so we make no guarantees.</p>
                        </div>
                    </div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Notification of Changes</legend>
                    <div class="row">
                        <div class="<?php echo $span; ?>">
                            <p>We may amend this Privacy Policy at any time by posting the amended terms on Sites. In the event of amendment, all terms shall become effective 30 days after they are initially posted to the Sites. Your continued use of Products or Services will constitute your acceptance of any changes or additions to this Privacy Policy.</p>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>

<?php
$data = <<<EOT

EOT;
echo $this->partial('_partials/helpContext.phtml', array('data' => $data));
?>