<div class="row">
    <div class="span12">
        <h1>Privacy</h1>

        <div class="row">
            <div class="span8">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt laboriosam debitis molestiae aliquam quod maiores deleniti dolores architecto distinctio repellendus ea odit. At quod reprehenderit accusantium ipsa laudantium fugit pariatur.</p>
                <p>Eveniet similique qui odit accusamus ducimus reiciendis molestiae rerum. Qui eveniet nesciunt veniam aperiam enim accusantium blanditiis fuga est quasi nam reprehenderit laboriosam voluptatum alias omnis eius provident dolorum labore.</p>
                <p>Officia reprehenderit perferendis quibusdam velit veniam? Inventore voluptatem totam incidunt aliquam repudiandae eius eos quisquam non eligendi fugiat similique commodi quos culpa quod amet nobis aliquid delectus ipsam rem itaque!</p>
            </div>
        </div>
    </div>
</div>