<div class="row">
    <div class="span12">
        <h1>Terms of Service</h1>

        <div class="row partner">
            <div class="span12">
                <p>These Terms of Service ("Terms") govern your access to and use of the services, including our various websites, SMS, APIs, email notifications, applications, buttons, and widgets, (the "Services" or “Twitter”), and any information, text, graphics, photos or other materials uploaded, downloaded or appearing on the Services (collectively referred to as "Content"). Your access to and use of the Services are conditioned on your acceptance of and compliance with these Terms. By accessing or using the Services you agree to be bound by these Terms.</p>
            </div>
        </div>

        <div class="form-box">
            <div class="box">
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>1. Basic Terms</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea quidem architecto dolorum eos inventore est atque blanditiis deleniti necessitatibus asperiores a vel non delectus ipsam accusamus alias veniam vitae voluptatibus.</p>
                            <p>Culpa facilis cum voluptas at explicabo numquam quia recusandae ad aliquid harum quasi pariatur possimus temporibus cupiditate fuga blanditiis itaque fugiat debitis expedita voluptatibus dolor dolore earum molestiae illo quam.</p>
                            <p>Ad eos nam ipsa dolores! Optio ducimus vero dolorem voluptatibus omnis soluta ipsa eligendi fuga earum vitae labore nesciunt magnam. Blanditiis deserunt hic dolorem temporibus voluptates molestias aliquid magni repellendus!</p>
                            <p>Labore eveniet odio nam accusantium recusandae unde sequi ducimus aliquid cumque impedit aperiam ab molestiae quidem fuga sed rem eaque quos illum architecto aspernatur voluptatum quia eius provident veritatis repellendus!</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>2. Privacy</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea quidem architecto dolorum eos inventore est atque blanditiis deleniti necessitatibus asperiores a vel non delectus ipsam accusamus alias veniam vitae voluptatibus.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>3. Passwords</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam culpa corrupti neque numquam debitis amet non quaerat facilis totam aperiam ratione explicabo adipisci voluptate fugit inventore enim nulla quisquam ea.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>4. Content on the Services</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam culpa corrupti neque numquam debitis amet non quaerat facilis totam aperiam ratione explicabo adipisci voluptate fugit inventore enim nulla quisquam ea.</p>
                            <p>Necessitatibus eveniet earum aliquam quos itaque quaerat voluptas fugiat. Aut unde sed necessitatibus corrupti asperiores nisi nostrum perferendis cum ad ipsa. Repellendus alias odit harum dolores rem molestiae esse sit. Dolorum velit non soluta id vero voluptas impedit rem saepe dolore eaque enim maxime ab molestias perspiciatis cupiditate odio autem nemo nulla eius aliquid architecto pariatur eum fugiat officiis blanditiis.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>5. Your Rights</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quisquam quo nemo debitis vero cum molestias commodi repellendus doloremque recusandae molestiae impedit rem! Perspiciatis neque voluptatum adipisci ullam nulla ut.</p>
                			<p>Eaque ipsum assumenda tempora blanditiis nobis animi quos saepe accusantium eum libero nemo inventore natus laborum molestias labore architecto ipsam ratione suscipit deserunt recusandae consectetur odit quisquam adipisci harum enim.</p>
                			<p>Quasi illo aspernatur amet nemo nobis eum hic maiores voluptatem deserunt sequi est perferendis consequatur minus beatae optio laboriosam fugiat assumenda cumque esse harum omnis natus aliquam eveniet quae necessitatibus!</p>
                			<p>Laudantium porro officia magni quidem cum quae repudiandae aspernatur sunt placeat sed dolor ex nobis ratione perspiciatis saepe pariatur minus tenetur molestias explicabo architecto voluptatem doloremque enim quis consequuntur eaque?</p>
                			<p>Earum veniam delectus reprehenderit quo blanditiis quasi in ut cum optio aliquid incidunt voluptatibus ea quisquam nemo praesentium rerum sapiente nisi corrupti libero assumenda atque voluptatem accusantium velit odio cumque?</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>6. Your License To Use the Services</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat totam iste animi quae repellendus consequatur quas iure. Sit minima quam velit tempore fuga quasi eaque mollitia fugit placeat nostrum eveniet.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>7. Twitter Rights</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id et quam quidem maiores earum neque ducimus tenetur enim fugiat accusamus eius rerum. Magnam tempore non vitae voluptatum facilis id est. Adipisci explicabo ad voluptates suscipit dolores dolorum inventore dolor non vero corporis ut earum minus sunt eum assumenda architecto quae numquam eos commodi placeat. Ab suscipit doloremque perspiciatis placeat tempora.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>8. Restrictions on Content and Use of the Services</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt magni quam explicabo impedit et molestiae at. Error sunt accusamus odio ratione ducimus explicabo dolorem deleniti beatae reprehenderit recusandae molestiae debitis.</p>
                			<p>Eaque minima nisi nemo dolorum id dolore molestiae tenetur delectus doloremque deserunt eum fuga repellat minus voluptatibus cupiditate autem beatae. Dicta nulla suscipit repellat soluta aperiam architecto quidem pariatur molestias.</p>
                			<p>Doloribus tempore unde saepe sapiente est iste eveniet quis asperiores perspiciatis similique vero quam incidunt quidem modi explicabo beatae praesentium doloremque labore eius totam? Voluptatum fugiat architecto expedita similique rem. Cumque voluptatem dolor omnis. Dolorum tempore in ipsum explicabo corrupti temporibus minima. Pariatur vero error quo eveniet libero fugiat ea accusantium explicabo impedit totam suscipit quidem veniam iste doloribus beatae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt magni quam explicabo impedit et molestiae at. Error sunt accusamus odio ratione ducimus explicabo dolorem deleniti beatae reprehenderit recusandae molestiae debitis.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>9. Copyright Policy</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Doloribus tempore unde saepe sapiente est iste eveniet quis asperiores perspiciatis similique vero quam incidunt quidem modi explicabo beatae praesentium doloremque labore eius totam? Voluptatum fugiat architecto expedita similique rem. Cumque voluptatem dolor omnis. Dolorum tempore in ipsum explicabo corrupti temporibus minima. Pariatur vero error quo eveniet libero fugiat ea accusantium explicabo impedit totam suscipit quidem veniam iste doloribus beatae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt magni quam explicabo impedit et molestiae at. Error sunt accusamus odio ratione ducimus explicabo dolorem deleniti beatae reprehenderit recusandae molestiae debitis.</p>
                			<p>Tenetur ratione possimus aliquam quam nisi itaque tempore laboriosam nesciunt cupiditate quidem doloribus eveniet quas non saepe architecto incidunt sapiente labore voluptatibus veniam aperiam a exercitationem numquam necessitatibus deleniti quisquam.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>10. Ending These Terms</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem aut optio ab explicabo cum vitae dolore aliquam nihil placeat quos dolorum modi similique debitis. Recusandae adipisci quibusdam voluptates corrupti impedit!</p>
                			<p>Assumenda commodi reprehenderit animi totam tempore magnam ullam quos saepe iusto est accusantium esse similique magni accusamus repellendus quisquam illum. Voluptas hic alias ullam itaque ad voluptates sint natus necessitatibus.</p>
                			<p>Recusandae consequuntur culpa vitae reprehenderit eveniet deleniti odit alias nesciunt officia nemo debitis numquam rem voluptatibus magnam ratione voluptate enim beatae inventore ea temporibus id! Sed vitae vero incidunt quae.</p>
                			<p>Quo fuga vel amet officiis quia delectus sunt nam architecto laborum odit aliquam illum nulla maxime ea incidunt repellendus iusto consequatur doloremque magnam ducimus iure earum similique nihil totam ab.</p>
                		</div>
                	</div>
                </fieldset>
                <div class="tab-stripe"></div>
                <fieldset>
                	<legend>10. Ending These Terms</legend>
                	<div class="row">
                		<div class="span11">
                			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem aut optio ab explicabo cum vitae dolore aliquam nihil placeat quos dolorum modi similique debitis. Recusandae adipisci quibusdam voluptates corrupti impedit!</p>
                			<p>Assumenda commodi reprehenderit animi totam tempore magnam ullam quos saepe iusto est accusantium esse similique magni accusamus repellendus quisquam illum. Voluptas hic alias ullam itaque ad voluptates sint natus necessitatibus.</p>
                			<p>Recusandae consequuntur culpa vitae reprehenderit eveniet deleniti odit alias nesciunt officia nemo debitis numquam rem voluptatibus magnam ratione voluptate enim beatae inventore ea temporibus id! Sed vitae vero incidunt quae.</p>
                			<p>Quo fuga vel amet officiis quia delectus sunt nam architecto laborum odit aliquam illum nulla maxime ea incidunt repellendus iusto consequatur doloremque magnam ducimus iure earum similique nihil totam ab.</p>
                		</div>
                	</div>
                </fieldset>
            </div>
        </div>
    </div>
</div>