<?php echo $this->render('_partials/helpBreadcrumbs.phtml'); ?>

<div class="row">
    <div class="span12 help">
        
        <?php echo $this->render('_partials/helpSideMenu.phtml'); ?>

        <div class="span9 help-main">
            <div class="form-box">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <div class="row">
                        <div class="span8">
                            <h3>Some article title goes here - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</h3>
                        </div>
                        <div class="span8 content">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, praesentium, dignissimos ex officiis sequi quos magnam sapiente aliquid voluptates autem sit possimus aspernatur repellendus soluta earum nemo sunt error libero!</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, repellendus, hic, quae asperiores voluptates explicabo nulla culpa odio excepturi dolorem animi aliquid omnis deserunt nemo iure numquam labore necessitatibus consequatur.</p>
                            <p>Voluptas, ipsum laborum nam fugiat nisi quas magni iste dolores libero corrupti! Illo, consectetur, error, quod iste esse incidunt enim rerum labore doloribus magni cupiditate rem molestias corrupti nesciunt explicabo!</p>
                            <p>Animi, beatae, repellendus reprehenderit exercitationem temporibus eligendi sequi ea possimus. Dolorum, tempore, perferendis doloribus officia recusandae reiciendis dolore quibusdam cupiditate in qui eius maxime officiis odit pariatur explicabo et quisquam!</p>
                            <p>Iste in id maiores perspiciatis expedita. Maiores, quisquam, doloribus perspiciatis nulla assumenda at molestiae pariatur nesciunt soluta harum itaque error labore modi illum ut ipsam tempore quas cum saepe ducimus.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>