<div class="row">
    <div class="span12">
        <form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <legend>
                <h3>Setup your custom environment</h3>
            </legend>
            <fieldset>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->instance_name ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->description ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->edition ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->version ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->custom_protocol ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->custom_host ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->custom_remote_path ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->custom_sql ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->custom_login ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->custom_pass ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->custom_file ?>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button type="submit" name="<?php echo $this->form->instanceAdd->getName(); ?>" id="<?php echo $this->form->instanceAdd->getId() ?>" class="btn btn-primary pull-right">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->instanceAdd->getLabel() ?>
                </button>
            </div>
        </form>
    </div>
</div>