<div class="row">
    <div class="span12">
	    <h1>Setup your custom environment</h1>
        <div class="form-box">
            <div class="box">
            	<form action="<?php echo $this->form->getAction() ?>"
            	    enctype="<?php echo $this->form->getEnctype() ?>"
            	    method="<?php echo $this->form->getMethod() ?>"
            	    id="<?php echo $this->form->getId() ?>"
            	    class="<?php echo $this->form->getAttrib('class') ?>">
            	    
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset class="margins">
            	        <legend>Store details</legend>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->instance_name ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->description ?>
            	            </div>
            	        </div>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->edition ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->version ?>
            	            </div>
            	        </div>
            	    </fieldset>
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset class="margins">
            	        <legend>Connection details</legend>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->custom_protocol ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->custom_host ?>
            	            </div>
            	        </div>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->custom_login ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->custom_pass ?>
            	            </div>
            	        </div>
            	    </fieldset>
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset class="margins">
            	        <legend>Store files and database</legend>
            	        <div class="input-radio">
            	        	<div class="row row-large">
            	        	    <div class="span8 input-radio-option">
            	        	        <?php echo $this->form->custom_remote_path ?>
            	        	    </div>
            	        	</div>
            	        	<div class="row row-large">
            	        	    <div class="span8 input-radio-option">
            	        	        <?php echo $this->form->custom_sql ?>
            	        	    </div>
            	        	</div>
            	        	<div class="row row-large">
            	        	    <div class="span8 input-radio-option">
            	        	        <?php echo $this->form->custom_file ?>
            	        	    </div>
            	        	</div>
            	        </div>
            	    </fieldset>
            	    
            	    
            	    <div class="form-actions">
            	        <button type="submit" name="<?php echo $this->form->instanceAdd->getName(); ?>" id="<?php echo $this->form->instanceAdd->getId() ?>" class="btn btn-inverse pull-right">
            	            <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->instanceAdd->getLabel() ?>
            	        </button>
            	    </div>
            	</form>
            </div>
        </div>
    </div>
</div>