<div class="row">
    <div class="span12">
	    <h1>Import your Magento store</h1>
        <div class="form-box">
            <div class="box">
            	<form action="<?php echo $this->form->getAction() ?>"
            	    enctype="<?php echo $this->form->getEnctype() ?>"
            	    method="<?php echo $this->form->getMethod() ?>"
            	    id="<?php echo $this->form->getId() ?>"
            	    class="<?php echo $this->form->getAttrib('class') ?>">
            	    
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset>
            	        <legend>Mage Testing Store Details</legend>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->store_name ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->description ?>
            	            </div>
            	        </div>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->edition ?>
            	            </div>
            	            <div class="span4">
                                <label for="version" class="control-label required">Version</label>
                                <select name="version" id="version-CE" class="span4" style="display: none;">
                                    <?php foreach($this->versions as $version): if($version->getEdition() == 'CE'):?>
                                        <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                    <?php endif; endforeach; ?>
                                </select>
                                <select name="version" id="version-EE" class="span4" style="display: none;">
                                    <?php foreach($this->versions as $version): if($version->getEdition() == 'EE'): ?>
                                        <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                    <?php endif; endforeach; ?>
                                </select>
                                <select name="version" id="version-PE" class="span4" style="display: none;">
                                    <?php foreach($this->versions as $version): if($version->getEdition() == 'PE'): ?>
                                        <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                    <?php endif; endforeach; ?>
                                </select>
            	                <?php //echo $this->form->version ?>
            	            </div>
            	        </div>
            	    </fieldset>
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset>
            	        <legend>Current Store Connection Details</legend>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->custom_protocol ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->custom_host ?>
            	            </div>
            	        </div>
                        <div class="row">
            	            <div class="span4">
            	                
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->custom_port ?>
            	            </div>
            	        </div>
            	        <div class="row">
            	            <div class="span4">
            	                <?php echo $this->form->custom_login ?>
            	            </div>
            	            <div class="span4">
            	                <?php echo $this->form->custom_pass ?>
            	            </div>
            	        </div>
            	        <a class="btn tooltip-top validate-connection-details" data-loading-text="Loading..." data-title="We will check if connection details are correct and we will try to look for your store location.">Validate connection details</a>
            	    </fieldset>
            	    
            	    <div class="tab-stripe"></div>
            	    <fieldset>
            	        <legend>Current Store Files and Database</legend>
            	        <div class="input-radio">
            	        	<div class="row">
            	        	    <div class="span1 input-radio-button">
            	        	        <input type="radio" <?php echo ($this->input_radio == 'remote_path' ? 'checked="checked"' : ''); ?> name="input-radio" value="remote_path" class="span1 pull-right">
            	        	    </div>
            	        	    <div class="span7 input-radio-option">
            	        	        <div class="input-radio-alert alert alert-<?php echo ($this->input_radio == 'remote_path' ? 'info' : 'blank'); ?>">
            	        	            <?php echo $this->form->custom_remote_path ?>
            	        	        </div>
            	        	    </div>
            	        	</div>
            	        	<div class="row">
            	        	    <div class="span1 input-radio-button">
                                    <input type="radio" <?php echo ($this->input_radio == 'file' ? 'checked="checked"' : ''); ?> name="input-radio" value="file" class="span1 pull-right">
            	        	    </div>
            	        	    <div class="span7 input-radio-option">
            	        	        <div class="input-radio-alert alert alert-<?php echo ($this->input_radio == 'file' ? 'info' : 'blank'); ?>">
            	        	            <?php echo $this->form->custom_file ?>
            	        	        </div>
            	        	    </div>
            	        	</div>
            	        </div>
            	        <div class="row row-large">
                            <div class="span8">
                                <div class="input-append">
                                <?php echo $this->form->custom_sql ?>
                                <span class="add-on tooltip-top find-sql-file btn" data-loading-text="Loading..." data-title="Find Latest Magento Admin Database Backup">Find database backup</span>
                            </div>
                        </div>
            	    </fieldset>
            	    
            	    <div class="form-actions">
            	        <button type="submit" name="<?php echo $this->form->storeAdd->getName(); ?>" id="<?php echo $this->form->storeAdd->getId() ?>" class="btn btn-inverse pull-right">
            	            <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->storeAdd->getLabel() ?>
            	        </button>
            	    </div>
            	</form>
            </div>
        </div>
    </div>
</div>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>
    