<div class="row">
    <div class="span12">
        <h1>Install a Clean Magento Demo Store</h1>
        <div class="form-box">
	        <div class="box">
	        	<form action="<?php echo $this->form->getAction() ?>"
	        	    enctype="<?php echo $this->form->getEnctype() ?>"
	        	    method="<?php echo $this->form->getMethod() ?>"
	        	    id="<?php echo $this->form->getId() ?>"
	        	    class="<?php echo $this->form->getAttrib('class') ?>">
	        	    
	        	    <div class="tab-stripe"></div>
	        	    <fieldset>
	        	    	<legend>Store Details</legend>
	        	    	<div class="row">
	        	        	<div class="span4">
	        	        	    <?php echo $this->form->store_name ?>
	        	        	</div>
	        	        	<div class="span4">
	        	        	    <?php echo $this->form->description ?>
	        	        	</div>
	        	        </div>
	        	        <div class="row">
	        	        	<div class="span4">
	        	        	    <?php echo $this->form->edition ?>
	        	        	</div>
	        	        	<div class="span4">
                                            <label for="version" class="control-label required">Version</label>
                                            <select name="version" id="version-CE" class="span4" style="display: none;">
                                                <?php foreach($this->versions as $version): if($version->getEdition() == 'CE'):?>
                                                    <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                                <?php endif; endforeach; ?>
                                            </select>
                                            <select name="version" id="version-EE" class="span4" style="display: none;">
                                                <?php foreach($this->versions as $version): if($version->getEdition() == 'EE'): ?>
                                                    <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                                <?php endif; endforeach; ?>
                                            </select>
                                            <select name="version" id="version-PE" class="span4" style="display: none;">
                                                <?php foreach($this->versions as $version): if($version->getEdition() == 'PE'): ?>
                                                    <option value="<?php echo $version->getId(); ?>" class="<?php echo $version->getEdition(); ?>"><?php echo $version->getVersion(); ?></option>
                                                <?php endif; endforeach; ?>
                                            </select>
	        	        	</div>
	        	        </div>
	        	    </fieldset>
	        	    
	        	    <div class="tab-stripe"></div>
	        	    <fieldset>
	        	        <legend>Store Files and Database</legend>
	        	    	<div class="row">
                                    <div class="span4">
                                            <?php echo $this->form->sample_data ?>
                                    </div>
                                    <div class="span8">
                                        <div class="alert alert-info">
                                            Install sample data installs a demo Magento store with populated products. No sample data installs basic Magento frontend with no products.
                                        </div>
                                    </div>
	        	    	</div>
	        	    	<?php if($this->userplan->getCanDoDbRevert()): ?>
	        	    	<div class="row">
                                    <div class="span4">
                                            <?php echo $this->form->do_hourly_db_revert ?>
                                    </div>
                                    <div class="span8">
                                        <div class="alert alert-info">
                                            Revert database hourly to the latest dump. This allows you to create an auto-cleaning demo site.
                                        </div>
                                    </div>
	        	    	</div>
	        	    	<?php endif; ?>
	        	    </fieldset>
	        	    
	        	    <div class="form-actions">
	        	        <button type="submit" name="<?php echo $this->form->storeAdd->getName(); ?>" id="<?php echo $this->form->storeAdd->getId() ?>" class="btn btn-inverse pull-right">
	        	            <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->storeAdd->getLabel() ?>
	        	        </button>
	        	    </div>
	        	</form>
	        </div>
	    </div>
    </div>
</div>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>