<div class="row">
    <div class="span12">
        <h1>Add New Magento Store</h1>
    </div>
    
    <div class="hidden-desktop hidden-tablet">
    	<div class="span6">
    	    <div class="form-box">
    	        <div class="box">
    	            <div class="tab-stripe"></div>
    	            <fieldset>
    	            	<legend class="remove-typekit">
    	            	    <a href="<?php echo $this->url(array('controller' => 'queue', 'action' => 'add-clean')) ?>"
                                class="btn btn-blue btn-large btn-block"><i class="icon-plus icon-white"></i>&nbsp;Clean Magento Demo Store</a>
                        </legend>
                        <div class="row" style="margin-bottom: 12px">
                            <strong>Difficulty:</strong> Easy
                        </div>
                        <div class="row">
                          	<strong>Who is it for?</strong>
                           	<p>Anyone who wants to test extensions on any magento version from 1.4.2 to the latest stable version, test themes or custom code.</p>
                        </div>
    	            </fieldset>
    	        </div>
    	    </div>
    	</div>
    	<?php if ($this->userGroup != 'free-user' && $this->userPlan->getCanAddCustomStore()==1): ?>
    	<div class="span6">
    	    <div class="form-box">
    	        <div class="box">
    	            <div class="tab-stripe"></div>
    	            <fieldset>
    	            	<legend class="remove-typekit">
                            <a href="<?php echo $this->url(array('controller' => 'queue', 'action' => 'add-custom')) ?>"
                                       class="btn btn-red btn-large btn-block"><i class="icon-plus icon-white"></i>&nbsp;Import My Store</a>
                        </legend>
                        <div class="row" style="margin-bottom: 12px">
                            <strong>Difficulty:</strong> Medium
                        </div>
                        <div class="row">
                            <strong>Who is it for?</strong>
                            <p>Anyone who already owns a 1.4.2 or greater Magento store and wants to test how new extensions will work with their current configuration and code.</p>
                        </div>
    	            </fieldset>
    	        </div>
    	    </div>
    	</div>
    	<?php endif; ?>
    </div>
    
    <div class="visible-desktop visible-tablet">
    	<div class="span12">
    	    <div class="form-box">
    	        <div class="box">
    	            <div class="tab-stripe"></div>
    	            <fieldset>
    	                <legend>&nbsp;</legend>
    	                <div class="row">
    	                    <div class="span3">
    	                        <strong>Choose One</strong>
    	                    </div>
    	                    <div class="span4">
    	                        <a href="<?php echo $this->url(array('controller' => 'queue', 'action' => 'add-clean')) ?>"
    	                            class="btn btn-blue btn-large btn-block"><i class="icon-plus icon-white"></i>&nbsp;Clean Magento Demo Store</a>
    	                    </div>
    	                    <?php if ($this->userGroup != 'free-user' && $this->userPlan->getCanAddCustomStore()==1): ?>
    	                        <div class="span4">
    	                            <a href="<?php echo $this->url(array('controller' => 'queue', 'action' => 'add-custom')) ?>"
    	                               class="btn btn-red btn-large btn-block"><i class="icon-plus icon-white"></i>&nbsp;Import My Store</a>
    	                        </div>
    	                    <?php endif; ?>
    	                </div>
    	               
    	                <hr />
    	                <div class="row">
    	                    <div class="span3"><strong>Difficulty</strong></div>
    	                    <div class="span4">Easy</div>
    	                    <?php if ($this->userGroup != 'free-user' && $this->userPlan->getCanAddCustomStore()==1): ?>
    	                    <div class="span4">Medium</div>
    	                    <?php endif; ?>
    	                </div>
    	                
    	                <hr />
    	                <div class="row">
    	                	<div class="span3"><strong>Who is it for?</strong></div>
    	                	<div class="span4">Anyone who wants to test extensions on any magento version from 1.4.2 to the latest stable version, test themes or custom code.</div>
    	                	<?php if ($this->userGroup != 'free-user' && $this->userPlan->getCanAddCustomStore()==1): ?>
    	                    <div class="span4">Anyone who already owns a 1.4.2 or greater Magento store and wants to test how new extensions will work with their current configuration and code.</div>
    	                    <?php endif; ?>
    	                </div>
    	            </fieldset>
    	        </div>
    	    </div>
    	</div>
    </div>
</div>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data));