<form action="" method="post">
    <fieldset>
        <legend>Setup your environment</legend>

        <?php echo $this->form->edition ?>
        <?php echo $this->form->version ?>

    </fieldset>
    <div class="actions">
        <?php echo $this->form->queueAdd; ?>
    </div>
</form>

<script type="text/javascript">
    $("#edition").change(function(){
        
        $.ajax({
            type: "POST",
            url: "<?php echo $this->baseUrl('queue/getVersions');?>",
            data: "edition="+ $("#edition").val(),
            dataType: "json",
            success: function(json){
                var opts = '';
                console.log(json);

                $.each(json,function(index, item){
                    opts =  opts +'<option value="'+ item.id +'">' + item.version + '</option>';
                });

                $("#version").html(opts);
            }

        });
        
    });
    </script>
