<fieldset><legend>Do you really want to remove this store?  There is no undo.</legend></fieldset>
<div class="row">
    <div class="span2">&nbsp;</div>
    <div class="yes-no">
        <form method="post">
                <?php echo $this->form->close ?>
            <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-primary">
                <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel() ?>
            </button>
        </form>
        <form method="post">
                <?php
                    $this->form->changeToNoForm();
                    echo $this->form->close;
                ?>
            <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn">
                <i class="icon-remove"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
            </button>
        </form>
        <div class="clear"></div>
    </div>
</div>