<div class="row">
    <div class="span8 offset2">
        <form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <div class="modal-header">
                <h3><h3>Select repo extensions to install</h3></h3>
            </div>
            <div class="modal-body">
                <fieldset>
                    <?php echo $this->form->extension ?>
                    <?php echo $this->form->instance_name ?>
                </fieldset>
            </div>
            <div class="modal-footer">
                <button type="submit" name="<?php echo $this->form->extensionAdd->getName(); ?>" id="<?php echo $this->form->extensionAdd->getId() ?>" class="btn btn-primary">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->extensionAdd->getLabel() ?>
                </button>
            </div>
        </form>
    </div>
</div>