<div class="row store-edit">
    <div class="span12">
        <h1>Edit Your Magento Store</h1>
        <div class="form-box">
        	<div class="box">
        		<form action="<?php echo $this->form->getAction() ?>"
        		    enctype="<?php echo $this->form->getEnctype() ?>"
        		    method="<?php echo $this->form->getMethod() ?>"
        		    id="<?php echo $this->form->getId() ?>"
        		    class="<?php echo $this->form->getAttrib('class') ?>">
        		
        			<div class="tab-stripe"></div>
        		    <fieldset>
        		        <legend>Store Details</legend>
        		        <div class="row">
        		        	<div class="span4"><?php echo $this->form->store_name ?></div>
        		        	<div class="span4"><?php echo $this->form->description ?></div>
        		        </div>
        		    </fieldset>
        		    
        		    <div class="tab-stripe"></div>
        		    <fieldset>
        		        <legend>Administration</legend>
        		        <div class="row">
        		            <div class="span4"><?php echo $this->form->backend_login ?></div>
        		            <div class="span4"><?php echo $this->form->backend_password ?></div>
        		        </div>
        		    </fieldset>
        		    
        		    <div class="tab-stripe"></div>
        		    <fieldset>
        		        <legend>Store Files and Database</legend>
	        	    	<div class="row db-revert-row">
                                    <div class="span4">
                                            <?php echo $this->form->do_hourly_db_revert ?>
                                    </div>
                                    <div class="span8">
                                        <div class="alert alert-info">
                                            Revert database hourly to latest version.  This lets you create an auto-cleaning demo site.
                                        </div>
                                    </div>
	        	    	</div>
        		    </fieldset>
        		    
        		    <!-- DO NOT RENDER THIS WHOLE BLOCK IF NOT NEEDED -->
                            <?php if ($this->store->getStatus()=='error'): ?>
        		    <div class="tab-stripe"></div>
        		    <fieldset>
        		        <legend>Remote details</legend>
        		        <div class="row">
        		            <div class="span4"><?php echo $this->form->custom_host; ?></div>
        		            <div class="span4"><?php echo $this->form->custom_login; ?></div>
        		        </div>
        		        <div class="row">
        		            <div class="span4"><?php echo $this->form->custom_pass; ?></div>
        		            <div class="span4"><?php echo $this->form->custom_pass_confirm; ?></div>
        		        </div>
        		        <div class="row">
        		            <div class="span4"><?php echo $this->form->custom_remote_path; ?></div>
        		            <div class="span4"><?php echo $this->form->custom_sql; ?></div>
        		        </div>
        		    </fieldset>
                            <?php endif; ?>
        		    <!-- DO NOT RENDER THIS WHOLE BLOCK IF NOT NEEDED -->
        		    
        		    <div class="form-actions">
        		        <button 
        		            type="submit"
        		            name="<?php echo $this->form->storeSave->getName(); ?>"
        		            class="btn btn-inverse pull-right">
        		        <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->storeSave->getLabel() ?></button>
        		    </div>
        		</form>
        	</div>
        </div>
    </div>
</div>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>