<div class="row instance-edit">
    <div class="span12">
        <form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <legend>
                <h3>Edit our store</h3>
            </legend>
            <fieldset>
            <?php echo $this->form->instance_name ?>
                <div class="row">
                    <div class="span6"><?php echo $this->form->backend_login ?></div>
                    <div class="span6"><?php echo $this->form->backend_password ?></div>
                </div>
                <div class="row">
                    <div class="span6"><?php echo $this->form->custom_host; ?></div>
                    <div class="span6"><?php echo $this->form->custom_login; ?></div>
                </div>
                <div class="row">
                    <div class="span6"><?php echo $this->form->custom_pass; ?></div>
                    <div class="span6"><?php echo $this->form->custom_pass_confirm; ?></div>
                </div>
                <div class="row">
                    <div class="span6"><?php echo $this->form->custom_remote_path; ?></div>
                    <div class="span6"><?php echo $this->form->custom_sql; ?></div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button 
                    type="submit"
                    name="<?php echo $this->form->instanceSave->getName(); ?>"
                    class="btn btn-primary pull-right">
                <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->instanceSave->getLabel() ?></button>
            </div>
        </form>
    </div>
</div>