<h1>Instance '<?php echo $this->form->instance_name->getValue(); ?>' Extensions</h1>
<form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
<input type="hidden" name="extension[]" id="new-instance-extension-id" />
<?php echo $this->form->instance_name ?>
<table class="table table-bordered table-striped">
    <thead>
        <th width="90%">Extension Name</th>
        <th width="10%">Installed</th>
    </thead>
    <tbody>
    <?php foreach($this->instance_extensions as $extension): ?>
    <tr>
        <td>
            <p class="pull-left">
                <b><?php echo $extension['name']; ?></b>
                <?php echo $extension['version'] ? '( '.$extension['version'].' )' : ''; ?><br />
                <?php echo $extension['description']; ?>
            </p>
            <span class="pull-right">
                <?php if((int)$extension['price']): ?>
                    <button class="btn btn-primary">Buy</button>
                <?php endif; ?>
                <button class="btn btn-success new-instance-extension-installer" data-extension-id="<?php echo $extension['id']; ?>">Install</button>
            </span>
        </td>

        <td><span class="label label-info">No</span></td>
    </tr>
    <?php endforeach; ?>
    <?php foreach($this->installed_extensions as $extension): ?>
    <tr>
        <td>
            <p class="pull-left">
                <b><?php echo $extension['name']; ?></b>
                <?php echo $extension['version'] ? '( '.$extension['version'].' )' : ''; ?>
            </p>
            <span class="pull-right">
                <button class="btn btn-danger">Remove</button>
            </span>
        </td>
        <td><span class="label label-success">Yes</span></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</form>
<div class="row">
    <div class="span8 offset2">
        <!--<form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <div class="modal-header">
                <h3>Select extensions to install</h3>
            </div>
            <div class="modal-body">
                <fieldset>
                    <?php echo $this->form->extension ?>
                    <?php echo $this->form->instance_name ?>
                    Installed Extensions:
                    <ul>
                    <?php foreach($this->old_installed_extensions as $iext): ?>
                        <li><?php echo $iext ?></li>
                    <?php endforeach; ?>
                    </ul>
                </fieldset>
            </div>
            <div class="modal-footer">
                <button type="submit" name="<?php echo $this->form->extensionAdd->getName(); ?>" id="<?php echo $this->form->extensionAdd->getId() ?>" class="btn btn-primary">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->extensionAdd->getLabel() ?>
                </button>
            </div>
        </form>-->
    </div>
</div>