<h1>Queue</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Name</th>
            <th>Status</th>
            <th>Edition</th>
            <th>Version</th>
            <th>Sample Data</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->queue as $item): ?>
        <tr>
            <td><?php echo $item['login']; ?></td>
            <td><?php echo $item['store_name']?></td>
            <?php 
                $progressClass = '';
                switch($item['status']): 
                    case 'ready':
                        $progressClass = 'label-success';
                    break; case 'closed':
                        $progressClass = 'label-danger';
                    break; case 'installing': 
                           case 'installing-extension':
                           case 'installing-magento':
                           case 'installing-samples':
                           case 'installing-user': 
                           case 'installing-files':
                           case 'installing-date': 
                        $progressClass = 'label-info install-bar';
                    break; case 'error': 
                        $progressClass = 'label-important';
                    break; default: 
                        $progressClass = 'label-info';
                endswitch;
            ?>
            <td>
            <?php
            $chunk = strpos($item['status'], '-');
            $chunk = ($chunk === false ? strlen($item['status']) : $chunk);
            switch(substr($item['status'], 0, $chunk)):
                case 'pending':
                case 'installing':
                case 'installing-extension':
                case 'installing-magento':
                case 'installing-samples':
                case 'installing-user':
                case 'installing-files':
                case 'installing-date':
            ?>
                <div class="progress progress-striped install-bar active" data-domain="<?php echo $item['domain']; ?>" style="margin-bottom:0px;margin-top:5px;">
                    <div class="bar" style="width: 100%;">
                    <?php if($item['status'] == 'pending'): ?>
                        In Queue - <?php echo $this->leftTime(Application_Model_Queue::getTimeLeftByStoreDomain($item['domain'])); ?>
                    <?php else: ?>
                        <?php echo ucwords(str_replace('-', ' ', $item['status'])); ?>
                    <?php endif; ?>
                    </div>
                </div>
            <?php break; default: ?>
                <span class="label <?php echo $progressClass; ?>"><?php echo ucwords(str_replace('-', ' ', $item['status'])); ?></span>
            <?php endswitch; ?>
            </td>
            <td><?php echo $item['edition']?></td>
            <td><?php echo $item['version']?></td>
            <td>
            <?php if($item['sample_data']): ?>
                <span class="label label-success">Yes</span>
            <?php else: ?>
                <span class="label label-important">No</span>
            <?php endif; ?>
            </td>
            <td>
            <?php if(in_array($item['status'], array('closed','pending','installing'))): ?>
                <a class="btn btn-success disabled"><i class="icon-white icon-eye-close"></i>&nbsp;Visit</a>
                <a class="btn btn-danger disabled"><i class="icon-white icon-trash"></i>&nbsp;Delete</a>
            <?php else: ?>
                <a href="<?php echo $this->baseUrl('store/'.$item['domain']); ?>" class="btn btn-success"><i class="icon-white icon-eye-open"></i>&nbsp;Visit</a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'close', 'domain' => $item['domain'], 'redirect' => 'admin'), 'default', true); ?>" class="btn btn-danger delete-store admin"><i class="icon-white icon-trash"></i>&nbsp;Delete</a>
            <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="close-store" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Delete Store</h3>
    </div>
    <div class="modal-body">
        <p>Do you really want to delete store<span class="close-store-name"></span>? There is no undo!</p>
    </div>
    <div class="modal-footer">
        <form method="post">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <input type="hidden" name="close" value="1" />
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

<?php echo $this->paginationControl($this->queue, 'Sliding', '_partials/paginationControl.phtml'); ?>