<h1>Queue</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Name</th>
            <th>Edition</th>
            <th>Version</th>
            <th>Sample Data</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->queue as $item): ?>
        <tr>
            <td><?php echo $item['login']; ?></td>
            <td><?php echo $item['instance_name']?></td>
            <td><?php echo $item['edition']?></td>
            <td><?php echo $item['version']?></td>
            <td>
            <?php if($item['sample_data']): ?>
                Yes
            <?php else: ?>
                No
            <?php endif; ?>
            </td>
            <?php switch($item['status']): 
            case 'ready':?>
                <td><span class="label label-success"><?php echo ucfirst($item['status']) ?></span> </td>
            <?php break; case 'pending':  ?>
                <td>
                    <span class="label label-warning">In Queue</span>
                    <span class="label">
                        <?php echo $item['queue_time']; ?>
                        minutes left
                    </span>
                </td>
            <?php break; case 'closed': ?>
                <td><span class="label label-important">Closed</span></td>
            <?php break; case 'installing': ?>
                <td><span class="label label-success">Installing..</span></td>
            <?php break; default: ?>
                <td><span class="label label-warning"></span></td>
            <?php endswitch; ?>
            <td>
            <?php if(in_array($item['status'], array('closed','pending'))): ?>
                <a class="btn btn-success disabled">Visit</a>
                <a class="btn btn-danger disabled">Close</a>
            <?php else: ?>
                <a href="<?php echo $this->baseUrl('instance/'.$item['domain']); ?>" class="btn btn-success">Visit</a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'close', 'domain' => $item['domain'], 'redirect' => 'admin'), 'default', true); ?>" class="btn btn-danger">Close</a>
            <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->queue, 'Sliding', '_partials/paginationControl.phtml'); ?>