<?php echo $this->render('_partials/helpBreadcrumbs.phtml'); ?>

<div class="row">
    <div class="span12 help">
        <h1>Deployment, rollbacks</h1>
        
        <?php echo $this->render('_partials/helpSideMenu.phtml'); ?>

        <div class="span9 help-main">
            <div class="form-box">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <div class="row">
                        <div class="span8">
                            <h3>Articles in this category</h3>
                            <ul>
                                <li>
                                    and no articles...
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>