<div class="row">
    <div class="span12 help">
        <h1>Need help?</h1>

        <div class="form-box">
            <div class="box">
                <div class="tab-stripe"></div>
                <div class="row">
                    <div class="span8">
                        <h3><a href="<?php echo $this->url(array('category' => 'some-category'), 'help-category') ?>">Some Category</a></h3>
                        <ul>
                            <li>
                                <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, ut labore et dolore magna aliqua.</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod dolore magna aliqua.</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-box help">
            <div class="box">
                <div class="tab-stripe"></div>
                <div class="row">
                    <div class="span8">
                        <h3>No Category here yet...</h3>
                        <ul>
                            <li>and no articles...</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-box help">
            <div class="box">
                <div class="tab-stripe"></div>
                <div class="row">
                    <div class="span8">
                        <h3>No Category here yet...</h3>
                        <ul>
                            <li>and no articles...</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>