<div class="row">
    <div class="span12 help">
        <h1>Need help?</h1>

        <div class="form-box">
            <div class="box">
                <div class="tab-stripe"></div>
                <div class="row">
                    <div class="span8">
                        <h3><a href="<?php echo $this->url(array('category' => 'importing-store'), 'help-category') ?>">Importing store</a></h3>
                        <ul>
                            <li>
                                <a href="<?php echo $this->url(array('category' => 'importing-store', 'page' => 'changes-in-imported-store'), 'help-page') ?>">Changes in imported store.</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-box help">
            <div class="box">
                <div class="tab-stripe"></div>
                <div class="row">
                    <div class="span8">
                        <h3>Deployment, rollbacks</h3>
                        <ul>
                            <li>and no articles...</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>