<?php echo $this->render('_partials/helpBreadcrumbs.phtml'); ?>

<div class="row">
    <div class="span12 help">
        <h1>Some Category</h1>
        
        <?php echo $this->render('_partials/helpSideMenu.phtml'); ?>

        <div class="span9 help-main">
            <div class="form-box">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <div class="row">
                        <div class="span8">
                            <h3>Articles in this category</h3>
                            <ul>
                                <li>
                                    <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, ut labore et dolore magna aliqua.</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('category' => 'some-category', 'page' => 'some-article'), 'help-page') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod dolore magna aliqua.</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>