<?php echo $this->render('_partials/helpBreadcrumbs.phtml'); ?>

<div class="row">
    <div class="span12 help">
        
        <?php echo $this->render('_partials/helpSideMenu.phtml'); ?>

        <div class="span9 help-main">
            <div class="form-box">
                <div class="box">
                    <div class="tab-stripe"></div>
                    <div class="row">
                        <div class="span8">
                            <h3>Preparing extension file.</h3>
                        </div>
                        <div class="span8 content">
                            <p>Packing extension to use that with Mage Testing is very easy and it's mainly about 
                                creating archive with proper directory layout.</p>

                            <h4>File format</h4>

                            <p>File containing extension files should be tarball compressed using gzip named with 
                                extension tar.gz or tgz. Content should be ready to paste into Magento root which means that <code>app/</code>, <code>js/</code>,
                                <code>lib/</code> and <code>skin/</code> directories should be placed in archive root. <code>app/</code> directory is required, 
                                other ones are optional.
                            </p>  

                            <p>Archive shouldn't have documentation or other files inside.</p>

                            <h4>Packing file example</h4>

                            <p>Sample command call looks as follow:</p>

                            <pre>tar czf extension.tar.gz -C directory/ .</pre>

                            <p>If command is being run on Mac OS X it's good to ignore dot files (._* like files) to avoid adding them into archive:</p>

                            <pre>export COPYFILE_DISABLE=true; tar czf extension.tar.gz -C directory/ .</pre>

                            <h4>Naming convention</h4>

                            <p>Extension package filename should follow VendorName_ExtensionKey-1.0.0.tar.gz naming convention eg.:</p>

                            <ul>
                                <li>AW_Blog-1.2.2.tgz</li>
                                <li>RocketWeb_GoogleBaseFeedGenerator-1.5.12.tar.gz</li>
                            </ul>
                            
                            <p>Packed extension is ready to upload to Mage Testing</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>