<legend>Are you sure you want to delete this item? There is no undo.</legend>
<div class="control-group">
    <div class="row">
        <div class="span2">&nbsp;</div>
        <div class="span2">
            <form method="post" class="form-inline">
                <?php echo $this->form->submit1; ?>
                <?php echo $this->form->submit2; ?>
            </form>
        </div>
    </div>
</div>