<div class="row">
    <div class="span12">
        <h1 class="pull-left">
            Plans
        </h1>
        <div class="pull-right btn-add-ext">
            <a href="<?php echo $this->url(array('controller' => 'plan', 'action' => 'add'), 'default', true); ?>" class="btn btn-blue btn-large"><i class="icon-plus icon-white"></i> Add New Plan</a>
        </div>
    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Plan name</th>
            <th>Price</th>
            <th>Is hidden</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->plans as $plan): ?>
        <tr>
            <td><?php echo $plan['name']; ?></td>
            <td><?php echo $plan['price']; ?></td>
            <td><?php echo ((int)$plan['is_hidden'] ? 'On' : 'Off'); ?></td>
            <td>
                <a href="<?php echo $this->url(array('module' => 'default', 
                    'controller' => 'plan',
                    'action' => 'edit',
                    'id' => $plan['id'])); ?>" class="btn btn-success"><i class="icon-white icon-pencil"></i>&nbsp;Edit</a>
                <a href="#plan-deletion" role="button" class="btn btn-danger plan-delete" data-toggle="modal" data-plan-id="<?php echo $plan['id']; ?>"><i class="icon-white icon-trash"></i>&nbsp;Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->plans, 'Sliding', '_partials/paginationControl.phtml'); ?>

<div id="plan-deletion" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Delete Plan</h3>
    </div>
    <div class="modal-body">
        <p>Are you sure you want to delete this plan: <b></b>? There is no undo.</p>
    </div>
    <div class="modal-footer">
        <form method="post" action="<?php echo $this->url(array('controller' => 'plan', 'action' => 'delete'), 'default', true); ?>">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <input type="hidden" name="confirm" value="1" />
            <input type="hidden" name="id" value="" />
            <button class="btn btn-danger" type="submit">Delete</button>
        </form>
    </div>
</div>