<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mage Testing</title>
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php
    $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('favicon.ico')));
    $this->headLink()->prependStylesheet($this->baseUrl('public/css/style.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('public/css/bootstrap-responsive.min.css'), 'screen');
    $this->headLink()->prependStylesheet($this->baseUrl('public/css/bootstrap.min.css'), 'print,screen');
    $this->headScript()->prependFile($this->baseUrl('public/js/custom.js'));
    $this->headScript()->prependFile($this->baseUrl('public/js/bootstrap.min.js'));
    $this->headScript()->prependFile($this->baseUrl('public/js/jquery-1.7.1.min.js'));
    $this->headScript()->prependFile($this->baseUrl('public/js/froogaloop2.min.js'));

    ?>

    <?php  ?>
    <script type="text/javascript" src="//use.typekit.net/qva5ffr.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

    <?php echo $this->headTitle() . "\n"; ?>
    <?php echo $this->headMeta() . "\n"; ?>
    <?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
    <?php echo $this->headStyle(); ?>

  </head>

<?php
    $uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
    $bodyClass = '';
    if($uri === "/"){
        $bodyClass = ' class="index"';
    }
?>
<body<?php echo $bodyClass;?>>
    <div id="wrap">
        <?php echo $this->render('_partials/globalHeader.phtml'); ?>

        <div id="main">
            <div class="container mt">
            <?php echo $this->render('_partials/messages.phtml'); ?>

            <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>

    <div id="footer">
        <div class="container">
            <footer>
                <hr />
                <div class="row">
                    <div class="span6">
                       <p>Copyright &copy; 2013 Rocket Web Inc. All rights reserved.</p>
                    </div>
                    <div class="span6">
                        <p class="links pull-right">
                            <a href="/about-us">About Us</a> |
                            <a href="/contact-us">Contact Us</a> |
                            <a href="/partners">Partners</a> |
                            <a href="/terms-of-service">Terms of Service</a> |
                            <a href="/privacy">Privacy</a>
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script>$('body').data('siteRoot', '<?php echo $this->serverUrl($this->baseUrl()); ?>');</script>
    <script type="text/javascript" src="//use.typekit.net/qva5ffr.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <?php echo $this->render('_partials/googleAnalytics.phtml'); ?>

</body>
</html>
