<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Magento Integration</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php 
  
    $this->headLink()->prependStylesheet($this->baseUrl('public/css/style.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('public/css/bootstrap.min.css'));
    $this->headScript()->prependFile($this->baseUrl('public/js/custom.js'));
    $this->headScript()->prependFile($this->baseUrl('public/js/bootstrap.min.js'));
    $this->headScript()->prependFile($this->baseUrl('public/js/jquery-1.7.1.min.js'));
    ?>
    
    <?php  ?>
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    
    <?php echo $this->headTitle() . "\n"; ?>
    <?php echo $this->headMeta() . "\n"; ?>
    <?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
    <?php echo $this->headStyle(); ?>
    
  </head>

<body>

    <div class="navbar navbar-fixed-top"> 
        <div class="navbar-inner navbar-fixed-top"> 
            <div class="container">
                <a class="brand"
                    href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">
                    Magento Integration</a>
                <?php echo $this->navigation()->menu()->setPartial(array('_partials/extendedTopMenu.phtml','default')); ?>
            </div>
        </div>
    </div>

    <div class="container">

        <?php echo $this->render('_partials/messages.phtml'); ?>

        <?php echo $this->layout()->content; ?>

        <hr />
        <footer>
            <p>&copy; Rocket Web 2011</p>
        </footer>

    </div>
    <!-- /container -->

</body>
</html>
