<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Magento Integration</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" ></script>
    
    <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('public/css/style.css')); ?>
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

<body>

    <div class="topbar">
        <div class="fill">
            <div class="container">
                <a class="brand"
                    href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">
                    Magento Integration</a>
                <!--<?php echo $this->navigation()->menu()->setULClass('nav')->renderMenu(null, array('minDepth' => 1, 'maxDepth' => 1)); ?>-->
                <ul class="nav" style="float: none;">
                    <li class="active"><a
                        href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Home</a>
                    </li>
                    <?php if($this->layout()->showDashboard): ?>
                        <li class="active" style="margin-left:3px;"><a
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'dashboard'), 'default', true); ?>">Dashboard</a>
                        </li>
                        <li class="active" style="float: right;"><a
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'logout'), 'default', true); ?>">Logout</a>
                        </li>
                    <?php else: ?>
                        <li class="active" style="float: right; margin-left: 3px;"><a
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'login'), 'default', true); ?>">Login</a>
                        </li>
                        <li class="active" style="float: right;"><a
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'register'), 'default', true); ?>">Create Account</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">

        <?php echo $this->layout()->content; ?>

        <footer>
            <p>&copy; Rocket Web 2011</p>
        </footer>

    </div>
    <!-- /container -->

</body>
</html>
