<h1>Plans comparision</h1>
<table class="table table-striped" >
  <thead>
    <tr>
      <th>X</th>
      <th>Free User</th>
      <th>Standard User</th>
      <th>Commercial User</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Instances</strong></td>
      <td><h2>1</h2></td>
      <td><h2>3</h2></td>
      <td><h2>10</h2></td>
    </tr>
    <tr>
      <td><strong>FTP Access</strong></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
    </tr>
    <tr>
      <td><strong>Mysql Access</strong></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
      <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
    </tr>
    <tr>
      <td><strong>Price</strong></td>
      <td><label class="btn btn-success">0$</label></td>
      <td><label class="btn">5$</label></td>
      <td><label class="btn btn-info">10$</label></td>
    </tr>
  </tbody>
</table>