<h1>Plans comparison</h1>
<?php $user = $this->user; ?>
<table class="table table-striped" >
    <thead>
        <tr>
            <th class="span4"></th>
            <th class="span3">Free User</th>
            <th class="span3">Standard User</th>
            <th class="span3">Business User</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>Instances</strong></td>
            <td><h2>1</h2></td>
            <td><h2>3</h2></td>
            <td><h2>10</h2></td>
        </tr>
        <tr>
            <td><strong>FTP Access</strong></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
        </tr>
        <tr>
            <td><strong>Mysql Access</strong></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
            <td><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
        </tr>
        <tr>
            <td><strong>Price</strong></td>
            <td>
                <label class="btn">Free!</label>
            </td>
            <td>
                <?php if(!$this->renderPayPal): ?>
                    <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'edit-account', 'inform' => '1')); ?>">
                        Subscribe for $5
                    </a>
                <?php else: ?>
                    <form class="paypal form-inline" action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="B43QP99JTYN8A">
                        <input type="hidden" name="address_override" value="1">
                        <input type="hidden" name="no_shipping" value="2">
                        <input type="hidden" name="custom" value="<?php echo $user->getId(); ?>:1">
                        <input type="hidden" name="address1" value="<?php echo $user->getStreet(); ?>">
                        <input type="hidden" name="city" value="<?php echo $user->getCity(); ?>">
                        <input type="hidden" name="country" value="<?php echo $user->getCountry(); ?>">
                        <input type="hidden" name="email" value="<?php echo $user->getEmail(); ?>">
                        <input type="hidden" name="first_name" value="<?php echo $user->getFirstname(); ?>">
                        <input type="hidden" name="last_name" value="<?php echo $user->getLastname(); ?>">
                        <input type="hidden" name="state" value="<?php echo $user->getState(); ?>">
                        <input type="hidden" name="zip" value="<?php echo $user->getPostalCode(); ?>">
                        <input class="btn btn-success" type="submit" name="submit" value="Subscribe for $5">
                    </form>
                <?php endif; ?>
            </td>
            <td>
                <?php if(!$this->renderPayPal): ?>
                    <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'edit-account', 'inform' => '1')); ?>">
                        Subscribe for $10
                    </a>
                <?php else: ?>
                    <form class="paypal form-inline" action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="KXJUYX7XBN52E">
                        <input type="hidden" name="no_shipping" value="2">
                        <input type="hidden" name="custom" value="<?php echo $user->getId(); ?>:2">
                        <input type="hidden" name="address1" value="<?php echo $user->getStreet(); ?>">
                        <input type="hidden" name="city" value="<?php echo $user->getCity(); ?>">
                        <input type="hidden" name="country" value="<?php echo $user->getCountry(); ?>">
                        <input type="hidden" name="email" value="<?php echo $user->getEmail(); ?>">
                        <input type="hidden" name="first_name" value="<?php echo $user->getFirstname(); ?>">
                        <input type="hidden" name="last_name" value="<?php echo $user->getLastname(); ?>">
                        <input type="hidden" name="state" value="<?php echo $user->getState(); ?>">
                        <input type="hidden" name="zip" value="<?php echo $user->getPostalCode(); ?>">
                        <input class="btn btn-success" type="submit" name="submit" value="Subscribe for $10">
                    </form>
                <?php endif; ?>
            </td>
        </tr>
    </tbody>
</table>