<!--[if IE]>
<style type="text/css" media="screen">
    th.compare-table-data-name {
        padding-top: 0;
        padding-bottom: 24px;
    }
</style>
<![endif]-->

<div class="row">
    <div class="span12">
        <h1>Mage Testing Plan Comparison and Pricing</h1>
        <?php $user = $this->user; ?>
        <table class="compare-table" style="margin-bottom: 20px">
            <thead>
                <tr class="compare-table-title-row">
                    <th class="compare-table-title-row"><span class="compare-table-title">Features</span></th>
                    <?php foreach($this->plans as $plan): ?>
                        <th class="compare-table-data-name">
                            <h3><span><?php echo $plan->getName(); ?></span></h3>
                            <h2><span class="compare-table-dollar">$</span><span><?php echo $plan->getPrice(); ?></span></h2>
                            <h4><span><?php echo $plan->getPriceDescription(); ?></span></h4>
                        </th>
                        <th class="compare-table-empty-first"><span class="compare-table-empty"></span></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Multiple Extension Testing" data-content="">
                            <i class="icon icon-blue icon-info-sign"></i> Multiple Extension Testing
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="One-click Extension install" data-content="">
                            <i class="icon icon-blue icon-info-sign"></i> One-click Extension install
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Purchase Tested Extensions" data-content="Once an extension is purchased you get an additional 7 day pass to Sandbox Exploration to access code and deploy to store site.">
                            <i class="icon icon-blue icon-info-sign"></i> Purchase Tested Extensions
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Rollback Capabilities" data-content="If you are not happy with extension you have installed you can easily uninstall that and test another extension.">
                            <i class="icon icon-blue icon-info-sign"></i> Rollback Capabilities
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Direct Extension Deployment" data-content="You can easily download package containing installed extension to apply changes on your live site.">
                            <i class="icon icon-blue icon-info-sign"></i> Direct Extension Deployment
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Real-time log files" data-content="Store logs are accessible in Papertrail for easy and fast debug.">
                            <i class="icon icon-blue icon-info-sign"></i> Real-time log files
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="FTP Access" data-content="You can get an FTP access to your store files to make any manual changes you need.">
                            <i class="icon icon-blue icon-info-sign"></i> FTP Access
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getFtpAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <?php /*
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <i class="icon icon-blue icon-info-sign"></i> phpMyAdmin Access
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getPhpmyadminAccess()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title">
                    <td class="compare-table-row-title">
                        <i class="icon icon-blue icon-info-sign"></i> Custom Store Import
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <?php if((int)$plan->getCanAddCustomStore()): ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/accept.png') ?>" alt="Yes"></td>
                            <td class="compare-table-empty"></td>
                        <?php else: ?>
                            <td class="compare-table-data"><img src="<?php echo $this->baseUrl('public/img/32x32/cancel.png') ?>" alt="No"></td>
                            <td class="compare-table-empty"></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>*/?>
                <tr class="compare-table-row-title compare-table-row-title-last">
                    <td class="compare-table-row-title  compare-table-row-title-last">
                        <div rel="popover" data-trigger="hover" data-placement="top" data-original-title="Access" data-content="">
                            <i class="icon icon-blue icon-info-sign"></i> Access
                        </div>
                    </td>
                    <?php foreach($this->plans as $plan): ?>
                        <td class="compare-table-data last-data"><?php echo $plan->getBillingDescription(); ?></td>
                        <td class="compare-table-empty last"></td>
                    <?php endforeach; ?>
                </tr>
                <tr class="compare-table-row-title-empty">
                    <td class="compare-table-price-empty empty-left"></td>
                    <?php $emptyCount = 0; ?>
                    <?php foreach($this->plans as $plan): ?>
                        <td class="compare-table-price-button">
                        <?php if(is_object($this->user)): ?>
                            <?php if($this->user->hasPlanActive() AND !(int)$this->user->getBraintreeTransactionConfirmed()): ?>
                            <button
                                type="button" 
                                <?php if($this->user->getBraintreeTransactionId()): ?>
                                title="Your payment for your current plan is being processed now. It make take up to 24 hours for this to complete.  You will be able to change your plan immediately after your initial payment has settled."
                                <?php endif; ?>
                                class="btn btn-large btn-success disabled subscribe-now">Subscribe Now</button>
                            <?php else: ?>
                            <form method="post" action="<?php echo $this->url(array('controller' => 'braintree', 'action' => 'payment'), 'default', true); ?>">
                                <input type="hidden" name="pay-for" value="<?php echo ($this->user->hasPlanActive() ? 'change-plan' : 'plan'); ?>" />
                                <input type="hidden" name="source" value="plan" />
                                <input type="hidden" name="id" value="<?php echo $plan->getId(); ?>" />
                                <button type="submit" class="btn btn-large btn-success">Get Started</button>
                            </form>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php $this->getHelper('ServerUrl')->setScheme('https'); ?>
                            <form method="post" action="<?php echo $this->serverUrl($this->url(array('controller' => 'user', 'action' => 'register'), 'default', true)); ?>">
                                <input type="hidden" name="preselected_plan_id" value="<?php echo $plan->getId(); ?>" />
                                <button type="submit" class="btn btn-large btn-success">Get Started</button>
                            </form>
                            <?php $this->getHelper('ServerUrl')->setScheme('http'); ?>
                        <?php endif;?>
                        </td>
                        <td class="compare-table-price-empty"></td>
                    <?php endforeach; ?>
                </tr>
                <?php /*
                <tr>
                    <td><strong>Paypal</strong></td>
                    <?php foreach($this->plans as $plan): ?>
                        <td>
                            <?php if(!$this->user->getSubscrId() && !$this->user->getBraintreeSubscriptionId()): ?>
                                <?php if(!$this->renderPayPal): ?>
                                    <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'edit-account', 'inform' => '1')); ?>">
                                        Subscribe for $<?php echo $plan->getPrice(); ?>
                                    </a>
                                <?php else: ?>
                                    <form class="paypal form-inline" action="https://www.paypal.com/cgi-bin/webscr" method="post">
                                        <input type="hidden" name="cmd" value="_s-xclick">
                                        <input type="hidden" name="hosted_button_id" value="<?php echo $plan->getPaypalId(); ?>">
                                        <input type="hidden" name="address_override" value="1">
                                        <input type="hidden" name="no_shipping" value="2">
                                        <input type="hidden" name="custom" value="<?php echo $user->getId(); ?>:1">
                                        <input type="hidden" name="address1" value="<?php echo $user->getStreet(); ?>">
                                        <input type="hidden" name="city" value="<?php echo $user->getCity(); ?>">
                                        <input type="hidden" name="country" value="<?php echo $user->getCountry(); ?>">
                                        <input type="hidden" name="email" value="<?php echo $user->getEmail(); ?>">
                                        <input type="hidden" name="first_name" value="<?php echo $user->getFirstname(); ?>">
                                        <input type="hidden" name="last_name" value="<?php echo $user->getLastname(); ?>">
                                        <input type="hidden" name="state" value="<?php echo $user->getState(); ?>">
                                        <input type="hidden" name="zip" value="<?php echo $user->getPostalCode(); ?>">
                                        <input class="btn btn-success" type="submit" name="submit" value="Subscribe for $<?php echo $plan->getprice(); ?>">
                                    </form>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php if ($this->user->getSubscrId()): ?>
                                    <a class="btn ctn-warning" href="#">Unsubscribe</a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td><strong>Credit Card</strong></td>
                    <?php foreach($this->plans as $plan): ?>
                        <td>
                            <?php if (!$this->user->getSubscrId() && !$this->user->getBraintreeSubscriptionId()): ?>
                                <?php if(!$this->renderBraintree): ?>
                                    <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'edit-account', 'inform' => '1')); ?>">
                                        Subscribe for $<?php echo $plan->getPrice(); ?>
                                    </a>
                                <?php else: ?>
                                    <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'braintree', 'action' => 'payment', 'plan' => $plan->getBraintreeId())); ?>">
                                        Subscribe for $<?php echo $plan->getPrice(); ?>
                                    </a>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php if ($this->user->getBraintreeSubscriptionId()): ?>
                                    <a class="btn btn-warning" href="<?php echo $this->url(array('controller' => 'braintree', 'action' => 'unsubscribe')); ?>">Unsubscribe</a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
                */ ?>
            </tbody>
        </table>
        
        <div class="row in-all-plans">
            <h4><span>Included in all plans</span></h4>
            <ul>
            	<li><i class="icon icon-blue icon-ok"></i> Test in empty Magento store</li>
            	<li><i class="icon icon-blue icon-ok"></i> Test in demo Magento store</li>
            	<li><i class="icon icon-blue icon-ok"></i> Test your Magento store</li>
            	<li><i class="icon icon-blue icon-ok"></i> Single domain</li>
            	<li><i class="icon icon-blue icon-ok"></i> Free extension store</li>
            	<li><i class="icon icon-blue icon-ok"></i> Premium extension store</li>
            </ul>
        </div>
    </div>
</div>
<div id="wrap-context-help">
    <div id="context-help">
        <div>
            <i class="icon-remove icon-white"></i>
            <h3>Help</h3>
            <ul>
                <li>Submit a Ticket</li>
                <li>Chat</li>
                <li>Documentation</li>
            </ul>
        </div>
    </div>
</div>