<div class="row">
    <div class="span10 offset1">
        <form
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <div class="modal-header">
                <h3>Edit Account</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->firstname; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->lastname; ?>
                    </div>
                </div>
                <br />
                <h4>Address</h4>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->street; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->postal_code; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->city; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->state; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->country; ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-primary">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
                </button>
                <button type="reset" name="<?php echo $this->form->reset->getName(); ?>" id="<?php echo $this->form->reset->getId() ?>" class="btn">
                    <i class="icon-repeat"></i>&nbsp;<?php echo $this->form->reset->getLabel(); ?>
                </button>
                <a href="<?php echo $this->url(array('controller' => 'my-account'), 'default', true); ?>" class="btn pull-left">Back</a>
            </div>
        </form>
    </div>
</div>