<div class="row">
    <div class="span12">
        <h1>Your Mage Testing Account Details</h1>
        <div class="form-box">
            <div class="box">
                
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Basic information</legend>
                    <div class="row">
                        <div class="span4">
                            <p class="user-name"><?php echo $this->escape($this->user->getFirstname()).' '.$this->escape($this->user->getLastname()); ?></p>
                            <p>Member since <?php echo date('F j, Y', strtotime($this->user->getAddedDate())); ?></p>
                        </div>
                        <div class="span3 offset1"><a class="btn btn-blue btn-block"href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'edit-account'), 'default', true); ?>">Edit account</a></div>
                    </div>
                </fieldset>
                
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Subscription</legend>
                        <div class="row">
                            <div class="span4">
                                <strong>Current plan:</strong>
                                <?php if($this->plan->getId()==0 OR !$this->user->hasPlanActive()): ?>
                                    None
                                <?php else:
                                if($this->user->hasPlanActive() AND $this->user->getBraintreeTransactionId() AND !(int)$this->user->getBraintreeTransactionConfirmed()){ 
                                
                                    echo '<div class="label label-warning">Pending</div>&nbsp;';
                                
                                }
                                echo $this->escape($this->plan->getName());  
                                endif;
                                ?>
                            </div>
                            <div class="span3 offset1">
                            <?php if((int)$this->user->getPlanId() AND $this->user->hasPlanActive() AND !(int)$this->user->getBraintreeTransactionConfirmed()): ?>
                                <button
                                    type="button"
                                    <?php if($this->user->getBraintreeTransactionId()): ?>
                                    title="Your payment for plan is being processed now. You will be able to change plan just after payment is settled."
                                    <?php endif; ?>
                                    class="btn btn-large btn-block btn-inverse change-plan disabled"
                                >
                                    Change Plan <i class="icon icon-white icon-share-alt"></i>
                                </button>
                            <?php else: ?>
                                <a class="btn btn-block btn-large btn-inverse" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'compare'), 'default', true); ?>">
                                <?php if($this->user->hasPlanActive() AND (int)$this->user->getPlanId()): ?>
                                    Change Plan
                                <?php else: ?>
                                    Select Plan
                                <?php endif; ?>
                                    <i class="icon icon-white icon-share-alt"></i>
                                </a>
                            <?php endif; ?>
                            </div>
                        </div>

                        <?php if($this->user->hasPlanActive()): ?>
                        <br />

                        <div class="row">
                            <div class="span8">
                                <div class="alert alert-info">
                                <?php if(!$this->user->getBraintreeTransactionId()):
                                    $coupon = new Application_Model_Coupon();
                                    $coupon->findByUser($this->user->getId());
                                ?>
                                    You have been granted access for <?php echo str_replace('+', '', $coupon->getDuration()); ?> of Mage Testing. Your account will be active until <?php echo date('F j, Y', strtotime($this->user->getPlanActiveTo())); ?>.
                                <?php elseif(!(int)$this->user->getBraintreeTransactionConfirmed()): ?>
                                    Your account is pending payment. It could take up to 24 hours to confirm your payment. Please enjoy using Mage Testing while we settle your payment details.
                                <?php elseif((int)$this->user->getPlanId() && $this->plan->getAutoRenew()): ?>
                                    Your next charge is $<?php echo $this->plan->getPrice();?> on <?php echo date("F j, Y", strtotime($this->user->getPlanActiveTo())) ?>
                                <?php elseif((int)$this->user->getPlanId()): ?>
                                    Your plan ends on <?php echo date("F j, Y",strtotime($this->user->getPlanActiveTo())) ?>
                                <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>

                        <?php if($this->raisedPlan instanceof Application_Model_Plan): ?>
                        <br />

                        <div class="row">
                            <div class="span8">
                                <div class="alert alert-success">
                                  <p><strong>Good news!</strong></p>
                                  <p>As you've purchased a Magento extension on our site, we have given you access to "<?php echo $this->raisedPlan->getName(); ?>" plan for 7 days for free.</p>
                                  <p>You can continue using the new plan until <?php echo date("F j, Y",strtotime($this->user->getPlanRaisedToDate())) ?>. After that your plan will be changed back to "<?php echo $this->escape($this->plan->getName()); ?>".</p> 
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>

                        <?php if (!$this->user->hasPlanActive()): ?>
                        <br />
                        <div class="row">
                          <div class="span4">Have a coupon code?</div> 
                          <div class="span8"><a class="btn btn-blue" href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'coupon')); ?>">Redeem your bonus!</a></div>
                        </div>
                        <?php endif; ?>
                    
                    
                    <?php /*
                    <div class="row">
                        <div class="span3">
                            <h3>Credit card</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span4">
                            Your credit card on file is xxxx-xxxx-xxxx-4837
                        </div>
                    </div>
                    <div class="row">
                        <div class="span4">
                            Note: You have 1 other account on this card
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="span4">
                            <a href="#">Change your credit card and billing information</a>
                        </div>
                    </div>
                    <hr />
                    */ ?>
                </fieldset>
                
                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Invoices</legend>
                    <?php if($this->payments): ?>
                        <?php foreach($this->payments as $payment): ?>
                        <div class="row">
                            <div class="span10">
                                <a href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'invoice', 'id' => $payment->getId()), 'default', true); ?>">
                                    <?php echo date('Ymd', strtotime($payment->getDate())).$payment->getUserId().$payment->getId(); ?>
                                </a>
                                 - <?php echo $payment->getTransactionName(); ?>
                                 - <?php echo date('m/d/Y', strtotime($payment->getDate())); ?>
                                 - $<?php echo $payment->getPrice(); ?>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="row"><div class="span4">You don't have any invoices</div></div>
                    <?php endif; ?>
                    <?php /* maybe in future someone change it to be responsive ?>
                    <?php if($this->payments): ?>
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Invoice #</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Date</th>
                                <th>Billing address</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->payments as $payment): ?>
                            <?php
                                $types = array(
                                    'subscription' => array('label' => 'Plan', 'class' => 'label-success'),
                                    'extension' => array('label' => 'Extension', 'class' => 'label-info')
                                );
                            ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url(array('controller' => 'my-account', 'action' => 'invoice', 'id' => $payment->getId()), 'default', true); ?>">
                                        <?php echo date('Ymd', strtotime($payment->getDate())).$payment->getUserId().$payment->getId(); ?>
                                    </a>
                                </td>
                                <td>
                                    <span class="label <?php echo $types[$payment->getTransactionType()]['class']; ?>"><?php echo $types[$payment->getTransactionType()]['label']; ?></span>
                                    <?php echo $payment->getTransactionName(); ?>
                                </td>
                                <td>$<?php echo $payment->getPrice(); ?></td>
                                <td><?php echo $payment->getDate(); ?></td>
                                <td>
                                    <?php echo $payment->getFirstName(), ' ', $payment->getLastName(); ?>
                                    <br />
                                    <?php echo $payment->getStreet(), ', ', $payment->getPostalCode(), ' ', $payment->getCity(); ?>
                                    <br />
                                    <?php echo $payment->getState(), ' ', $payment->getCountry(); ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php else: ?>
                    <div class="row"><div class="span4">You don't have any invoices</div></div>
                    <?php endif; ?>
                    <?php */ ?>
                </fieldset>
                
            </div>
        </div>
    </div>
</div>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>