<?php $this->headLink()->appendStylesheet($this->baseUrl('public/css/print.css'), 'print'); ?>
<?php //$this->headLink()->appendStylesheet($this->baseUrl('public/css/bootstrap-responsive.min.css'), 'print'); ?>
<?php //$this->headLink()->appendStylesheet($this->baseUrl('public/css/bootstrap.min.css'), 'print');?>
<?php $payment = $this->payment; ?>

<div class="row invoice">
    <div class="span12">
        <h1>Invoice #<?php echo date('Ymd', strtotime($payment->getDate())).$payment->getUserId().$payment->getId(); ?></h1>
        <div class="form-box">
            <div class="box">
                
                <div class="tab-stripe"></div>
                <fieldset class="invoice-details">
                    <legend>Invoice details</legend>
                    <div class="row">
                        <div class="span4 invoice-info invoice-address invoice-address-to">
                            <address>
                                <strong>Rocket Web Inc.</strong><br>
                                475 River Bend Rd<br>
                                Ste 200C<br>
                                Naperville, IL 60540<br>
                                USA<br>
                            </address>
                        </div>
                        <div class="span4 invoice-info-minor">
                            <div class="row in">
                            	<div class="span1"><h5>DATE:</h5></div>
                            	<div class="span2"><?php echo date('F d, Y', strtotime($payment->getDate()))?></div>
                            </div>
                            <div class="row">
                            	<div class="span1"><h5>INVOICE:</h5></div>
                            	<div class="span2">#<?php echo date('Ymd', strtotime($payment->getDate())).$payment->getUserId().$payment->getId(); ?></div>
                            </div>
                        </div>
                    </div>
                    <hr>
                	<div class="row invoice-addresses">
        		    	<div class="span4 invoice-address invoice-address-billto">
        		    		<h5>BILL TO:</h5>
        		    		<address>
        		    			<strong>
        		    			    <?php echo $payment->getFirstName(); ?>
        		    			    <?php echo $payment->getLastName(); ?>
        		    			</strong><br>
        		    			<?php echo $payment->getStreet(); $state = array_search($payment->getState(), RocketWeb_List::getStatesOfAmerica()); ?><br />
        		    			<?php echo $payment->getCity() . ', '. $state . ' ' . $payment->getPostalCode(); ?><br />
        		    			<?php echo $payment->getCountry(); ?>
        		    		</address>
        		    	</div>
                	</div>
                </fieldset>
                
                <div class="tab-stripe"></div>
                <fieldset class="invoice-purchase">
                	<legend>
                	    <?php if($payment->getTransactionType() == 'subscription'): ?>
                            Subscribed plan
                        <?php else: ?>
                            Bought Extension
                        <?php endif; ?>
                	</legend>
                	<div class="row">
                		<div class="span4 invoice-purchase-item"><?php echo $payment->getTransactionName(); ?></div>
                		<div class="span4 currency">$<?php echo $payment->getPrice(); ?></div>
                	</div>
                	<div class="row invoice-total">
                		<div class="span4 invoice-purchase-total"><strong>TOTAL:</strong></div>
                		<div class="span4 currency">$<?php echo $payment->getPrice(); ?></div>
                	</div>
                </fieldset>
            </div>
        </div>
    </div>
</div>