<?php
$class = '';
if ($this->element->hasErrors()) {
    $class .= ' error';
}
?>
<div class="control-group <?php echo $class; ?>">
    <label for="<?php echo $this->element->getFullyQualifiedName(); ?>" class="control-label required"><?php echo $this->element->getLabel(); ?></label>
    <div class="controls">
        <input class="file-upload" type="file" id="<?php echo $this->element->getFullyQualifiedName(); ?>" name="<?php echo $this->element->getFullyQualifiedName(); ?>" />
        <?php if($class): ?>
            <?php echo $this->formErrors($this->element->getMessages()); ?>
        <?php endif; ?>
    </div>
</div>
