<?php if($this->conflict['task'] === true): ?>
<div class="alert alert-success">Checking store extensions conflicts - please be patient as your request is being made.</div>
<?php endif;

echo '<br />'.$this->partial('_partials/conflictTable.phtml', array(
    'conflict' => $this->conflict,
    'button' => true,
    'ignored' => false
)); ?>
<?php
$ignoredSize = sizeOf($this->conflict['ignore']);
if($ignoredSize > 0): ?>
<br />
<a href="javascript:return false;" class="show-ignored-button">Show ignored conflicts (<?php echo $ignoredSize; ?>) ...</a>
<div class="hide">
    <h5>Ignored conflicts</h5>
    <?php echo $this->partial('_partials/conflictTable.phtml', array(
        'conflict' => $this->conflict,
        'button' => false,
        'ignored' => true
    )); ?>
</div>
<?php endif; ?>