<?php echo $this->partial('_partials/conflictTable.phtml', array(
    'conflict' => $this->conflict,
    'button' => true,
    'ignored' => false
)); ?>
<?php if(sizeOf($this->conflict['ignore']) > 0): ?>
<br />
<a href="#" class="show-ignored-button">Show ignored conflicts ...</a>
<div class="hide">
    <h5>Ignored conflicts</h5>
    <?php echo $this->partial('_partials/conflictTable.phtml', array(
        'conflict' => $this->conflict,
        'button' => false,
        'ignored' => true
    )); ?>
</div>
<?php endif; ?>