<!--CSS styling needed -->
<table class="table table-bordered table-striped">
    <tr>
        <th>Type</th>
        <th>Class</th>
        <th>Rewrites</th>
        <th>Loaded</th>
        <th style="text-align:center">
            <?php if($this->button === true): ?>
            <a href="#" class="btn btn-info rerun-button" title="Re-run extension check"><i class="icon-white icon-wrench"></i> Re-run</a></th>
            <?php endif; ?>
    </tr>
    <?php
    $data = $this->ignored ? $this->conflict['ignore'] : $this->conflict['conflicts'];
    if(sizeOf($data) == 0): ?>
        <tr><td colspan="5">No extensions conflicts!</td></tr>
    <?php else: ?>
        <?php foreach($data as $c): ?>
            <tr>
                <td><?php echo $c['type']; ?></td>
                <td><?php echo $c['class']; ?></td>
                <td><?php echo $c['rewrites']; ?></td>
                <td><?php echo $c['loaded']; ?></td>
                <td style="text-align:center">
                    <a href="#<?php echo $c['id']?>" class="btn btn-red <?php echo $this->ignored ? 'un' : ''?>ignore-conflict-button">
                        <i class="icon-white icon-wrench"></i> <?php echo $this->ignored ? 'Unignore' : 'Ignore'?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
