<?php foreach( $this->container as $name => $page ): ?>
<ul class="nav nav-mainmenu pull-right">
    <?php
        $index = 0;
        $allPages = 0;
        foreach( $page->pages as $subpage ){
            if($this->menu()->accept($subpage)){
                $allPages++;
            }
        }
    ?>
    
    <?php foreach( $page->pages as $subpage ): ?>
        <?php if($this->menu()->accept($subpage)):
        $class = array();
        if($subpage->isActive()) { $class[] = 'active'; }
        
        if($index === 0){ $class[] = 'first'; }
        if($index === $allPages - 1){ $class[] = 'last'; }
        
        $class = implode(' ',$class);

        if($subpage->label == 'My data' || $subpage->label == 'My account'){
            $user = Zend_Auth::getInstance()->getIdentity();
            $label = $user->firstname.' '.$user->lastname;
            $subpage->label = $label;
        }

        $numberOfDropPages = 0;
        if(count($subpage->pages)){
            $lastDropPage = null;
            foreach($subpage->pages as $dropPage){
                if($this->menu()->accept($dropPage)){
                    $numberOfDropPages++;
                    $lastDropPage = $dropPage;
                }
            }
            if($numberOfDropPages == 1){
                $subpage = $lastDropPage;
            }
        }
        ?>
        	<?php if($numberOfDropPages > 1): ?>
        	<li class="<?php echo $class; ?>">
        		<?php echo $this->iconMenu()->htmlify($subpage); ?>
				<ul class="dropdown-menu">
					<?php foreach( $subpage->pages as $dropdownpage ): ?>
                        <?php if($this->menu()->accept($dropdownpage)): ?>
					        <li><?php echo $this->iconMenu()->htmlify($dropdownpage); ?></li>
                        <?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</li>
            <?php else: ?>
            <li class="<?php echo $class; ?>">
                <?php echo $this->iconMenu()->htmlify($subpage); ?>
            </li>
			<?php endif; ?>
        <?php $index++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endforeach; ?>
