<?php foreach( $this->container as $name => $page ): ?>
<ul class="nav pull-right">
    <?php
        $index = 0;
        $allPages = 0;
        foreach( $page->pages as $subpage ){
            if($this->menu()->accept($subpage)){
                $allPages++;
            }
        }
    ?>
    
    <?php foreach( $page->pages as $subpage ): ?>
        <?php if($this->menu()->accept($subpage)):
        $class = array();
        if($subpage->isActive()) { $class[] = 'active'; }
        
        if($index === 0){ $class[] = 'first'; }
        if($index === $allPages - 1){ $class[] = 'last'; }
        
        $class = implode(' ',$class);
        ?>
        	<?php if(count($subpage->pages)): ?>
        	<li class="<?php echo $class; ?>">
        		<?php echo $this->iconMenu()->htmlify($subpage); ?>
				<ul class="dropdown-menu">
					<?php foreach( $subpage->pages as $dropdownpage ): ?>
					<li><?php echo $this->iconMenu()->htmlify($dropdownpage); ?></li>
					<?php endforeach; ?>
				</ul>
			</li>
            <?php else: ?>
            <li class="<?php echo $class; ?>">
                <?php echo $this->iconMenu()->htmlify($subpage); ?>
            </li>
			<?php endif; ?>
        <?php $index++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endforeach; ?>