<div class="span3 help-side pull-right clearfix">
    <div class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
            <li class="nav-header">Help Categories</li>
            <li class="active"><a href="/help/some-category">Some Category</a></li>
            <li><a href="/help/some-category">Some other category</a></li>
            <li><a href="/help/some-category">Some other category</a></li>
            <li><a href="/help/some-category">Some other category</a></li>
        </ul>
    </div>
</div>