<div id="wrap-context-help">
    <div id="context-help">
        <div>
            <i class="icon-remove icon-white"></i>
            <h3>Help</h3>
            <?php echo $this->data; ?>
            <div class="well well-small">
                <p>Please <a href="https://rocketwebinc.zendesk.com/anonymous_requests/new">Submit a Ticket</a> in order to get more help.</p>
            </div>
        </div>
    </div>
</div>