<div class="span3 help-side pull-right clearfix">
    <div class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
            <li class="nav-header">Help Categories</li>
        </ul>
        <?php $page = $this->navigation()->findById('help');
        echo $this->navigation()->menu()->setUlClass('nav nav-list')
                                        ->setMaxDepth(0)
                                        ->renderMenu($page); ?>
    </div>
</div>