<? if (is_array($this->messages) && count($this->messages)): ?>
    <?
        foreach ($this->messages as $msg):
        if(is_string($msg)) {
            $msg = array('message' => $msg);
        }
        $class = 'alert-success';
        switch( isset($msg['type']) ? $msg['type'] : 'success') {
            case 'error':
                $class = 'alert-error';
            break;
            case 'notice':
                $class = '';
            break;
        }
    ?>
        <div class="alert <?php echo $class; ?>" data-dismiss="alert">
            <a class="close" href="#">&times;</a>
            <?php if(isset($msg['from_scratch']) and $msg['from_scratch']): ?>
                <?php echo $msg['message']; ?>
            <?php else: ?>
                <strong><?php echo $this->escape($this->translate($msg['message'])); ?></strong>
            <?php endif; ?>
        </div>
    <? endforeach; ?>
<? endif; ?>