<?php $storeCount = $this->queue->getTotalItemCount(); ?>
<!-- START STORES PAGE -->
<div class="row">
    <div class="span12">
        <input id="base-url" type="hidden" value="<?php echo $this->baseUrl(); ?>" />

        <?php if($storeCount > 0 AND $storeCount < (int)$this->planModel->getStores()+(int)$this->user->additional_stores-(int)$this->user->additional_stores_removed): ?>
        <a href="<?php echo $this->url(array('controller'=>'queue', 'action' => 'add'))?>" class="btn btn-red pull-right"><i class="icon icon-white icon-plus-sign"></i> Add New Store</a>
        <?php elseif($storeCount > 0 && (int)$storeCount < (int)$this->planModel->getStores()+(int)$this->planModel->getMaxStores() && (int)$this->planModel->getStores()+(int)$this->user->additional_stores < (int)$this->planModel->getStores()+(int)$this->planModel->getMaxStores()): ?>
        <a href="<?php echo $this->url(array('controller'=>'payment', 'action' => 'additional-stores'))?>" class="btn btn-success pull-right"><i class="icon icon-white icon-plus-sign"></i> Purchase Additional Stores</a>
        <?php endif; ?>

        <h1>Your Magento Store</h1>
        <!-- START ACCORDION -->
        <div class="accordion" id="accordion">

        <?php /* IF USER HAS NO STORES */ ?>
        <?php if($storeCount === 0): ?>
            <!-- START STORE -->
            <div class="accordion-group accordion-add-new" data-active="0">
                <div class="accordion-heading hidden-phone">
                    <div class="accordion-toggle">
                        <div class="for-use ready pull-right">
                            <a target="_blank" href="#" class="btn btn-faded btn-mini view-store disabled"><i class="icon icon-white icon-home"></i> View Store</a>
                            <a href="#" class="btn btn-mini btn-faded admin-panel disabled"><i class="icon icon-white icon-wrench"></i> Access Admin</a>
                        </div>
                    </div>
                </div>
                <div class="accordion-body collapse in mt_store">
                    <div class="accordion-inner">
                        <?php if ($this->user->plan_id == 0 ): ?>
                            <a href="<?php echo $this->url(array('controller'=>'my-account', 'action' => 'compare'))?>" class="btn btn-red btn-select-plan-to-add"><i class="icon icon-white icon-plus-sign"></i> Select a plan to add your first store</a>
                        <?php else: ?>
                            <a href="<?php echo $this->url(array('controller'=>'queue', 'action' => 'add'))?>" class="btn btn-red btn-add-store"><i class="icon icon-white icon-plus-sign"></i> Add your first store</a>
                        <?php endif; ?>
                        <div class="row version-info hidden-phone">
                            <div class="span2 first"><strong>Edition:</strong></div>
                            <div class="span2"><strong>Version:</strong></div>
                            <div class="span2"><strong>Sample Data:</strong></div>
                        </div>
                        <p class="description hidden-phone"></p>
                        <div class="row hidden-phone">
                            <!-- START DETAILS BOX -->
                            <div class="span4 panel details">
                                <h5>Configuration</h5>
                                <div class="control-group">
                                    <div class="controls">
                                        <a href="#" class="btn btn-inverse btn-faded disabled"><i class="icon icon-cog"></i> Extensions</a>
                                        <a href="#" class="btn btn-faded disabled"><i class="icon icon-white icon-pencil"></i> Edit Details</a>
                                    </div>
                                </div>
                            </div>
                            <!-- END DETAILS BOX -->

                            <!-- START DEPLOYMENT BOX -->
                            <div class="span4 panel deployment">
                                <h5>Deployment</h5>
                                <div class="control-group">
                                    <div class="controls">
                                        <a href="#" class="btn btn-faded rollback-button disabled"><i class="icon icon-white icon-circle-arrow-left"></i> Rollback</a>
                                        <a href="#" class="btn btn-faded commit-button disabled" ><i class="icon icon-white icon-ok-sign"></i> Commit</a>
                                        <a href="#" class="btn btn-faded deploy-button disabled">Deploy <i class="icon icon-white icon-circle-arrow-right"></i> </a>
                                    </div>
                                </div>
                            </div>
                            <!-- END DEPLOYMENT BOX -->

                            <!-- START PROBLEMS BOX -->
                            <div class="span3 panel">
                                <h5>Troubleshooting</h5>
                                <div class="control-group">
                                    <div class="controls">
                                        <a href="#" class="btn btn-faded disabled"><i class="icon icon-white icon-info-sign"></i> Show Logs</a>
                                        <a target="_blank" href="#" class="btn btn-faded disabled"><i class="icon icon-white icon-question-sign"></i> Get Help</a>
                                    </div>
                                </div>
                            </div>
                            <!-- END PROBLEMS BOX -->
                        </div>

                    </div>
                </div>
            </div>
            <!-- END STORE -->
        <?php endif; ?>

        <?php /* IF USER HAS STORES */ ?>
        <?php if($storeCount > 0): $decryptor = new Application_Model_Store(); ?>
        <?php foreach ($this->queue as $key => $item): ?>
            <!-- START STORE -->
            <div class="accordion-group" data-active="0">
                <div class="accordion-heading">
                    <div class="tab-stripe"></div>
                    <div class="accordion-toggle store-toggle <?php echo ($item['status'] != 'ready' && $item['status'] != 'error')? 'installing' : ''; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $key; ?>" data-status="<?php echo ($item['status']) ?>">
                    <?php
                        $progressClass = '';
                        switch($item['status']):
                           case 'error':
                               $progressClass = 'progress-danger';
                               break;
                           default:
                               $progressClass = 'progress-info';
                        endswitch;
                    ?>  <div class="left-content">
                            <div class="arrow pull-left"><i class="icon icon-chevron-down icon-blue"></i></div>
                            <div class="store-name"><?php echo $this->escape($item['store_name']) ?></div>
                        </div>      
                        <div class="right-content pull-right inactive">
                            <div class="for-use <?php echo (in_array($item['status'], array('ready', 'error')) ? '' : 'hidden'); ?>">
                            <a href="<?php echo $this->url(array('controller' => 'queue','action'=> 'close','domain'=>$item['domain'])) ?>" class="btn btn-danger btn-mini delete-store pull-right"><i class="icon icon-white icon-remove"></i></a>
                            <?php if($item['status'] == 'ready'): ?>
                                <?php if(in_array($this->user->downgraded, array(
                                    Application_Model_User::DOWNGRADED_TOO_MANY_STORES_SYMLINKS_NOT_DELETED,
                                    Application_Model_User::DOWNGRADED_TOO_MANY_STORES_SYMLINKS_DELETED))): ?>
                                <a class="btn btn-faded btn-mini view-store disabled"><i class="icon icon-white icon-home"></i> View Store</a>
                                <a class="btn btn-mini btn-faded admin-panel disabled"><i class="icon icon-white icon-wrench"></i> Access Admin</a>
                                <?php else: ?>
                                <a
                                    class="btn btn-mini admin-panel pull-right"
                                    href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'login-to-store-backend', 'store' => $item['domain']), 'default', true); ?>"
                                ><i class="icon icon-wrench"></i> Access Admin</a>
                                <a target="_blank" href="<?php echo $this->getScheme().$this->user->login.'.'.$item['server_domain'].'/'.$item['domain']; ?>" class="btn btn-mini view-store pull-right"><i class="icon icon-home"></i> View Store</a>
                                <?php endif; ?>
                            <?php endif; ?>
                            </div>
                            <div class="in-use <?php echo ($item['status'] == 'ready' ? 'hidden' : ''), ($item['status'] == 'error' ? ' error-bar' : ''), ($item['status'] == 'downloading-magento' ? ' download-bar' : ''); ?>">
                                <?php if($item['status'] == 'error'): ?>
                                <span id="popover-error-dashboard" rel="popover" data-placement="bottom" data-original-title="Error" data-content="<?php echo ($item['error_message']) ? $item['error_message'] : 'Please click on Help button above to submit a support ticket.'  ?>" data-trigger="hover">
                                <?php endif; ?>
                                    <span class="span3 progress <?php echo $progressClass ?> progress-striped pull-right active" style="height:12px;" >
                                        <span class="bar" style="width: 100%;"></span>
                                    </span>
                                    <?php if($item['status'] == 'downloading-magento'): ?>
                                    <span class="pending pull-right">
                                        Creating site via FTP/SSH.  This may take 1 hour or more.  You will receive an email when this is complete.
                                    </span>
                                    <?php else: ?>
                                    <span class="pending pull-right statusHolder">
                                    <?php /*if($item['status'] == 'pending'): ?>
                                        In Queue - <?php echo (isset($this->queueCounter[$item['id']]) ?$this->queueCounter[$item['id']] : 0); ?> minutes left
                                    <?php else:*/ ?>
                                        <?php echo $this->niceStatus($item['status']); ?>
                                        <?php if($item['status'] != 'ready' && $item['status'] != 'error'): ?>
                                        - please be patient as your request is being made.
                                        <?php endif; ?>
                                    </span>
                                    <?php endif; ?>
                                <?php if($item['status'] == 'error'): ?>
                                </span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <input type="hidden" class="storedomain" value="<?php echo $this->escape($item['domain']) ?>" />
                        <input type="hidden" class="queueval" value="<?php echo $this->escape($item['queue_id']) ?>" />
                        <input type="hidden" class="userval" value="<?php echo $this->escape($item['user_id']) ?>" />
                    </div>
                </div>
                <?php if($item['status'] != 'closed'): ?>
                <div id="collapse<?php echo $key; ?>" class="accordion-body collapse mt_store">
                    <div class="accordion-inner">
                        <div class="row version-info">
                            <div class="span2 first"><strong>Edition:</strong> <?php echo $this->escape($item['edition']); ?></div>
                            <div class="span2 first"><strong>Version:</strong> <?php echo $this->escape($item['version']); ?> </div>
                            <div class="span2">
                                <strong>Sample Data:</strong>
                            <?php if($item['sample_data']): ?>
                                Yes
                            <?php else: ?>
                                No
                            <?php endif; ?>
                            </div>
                            <div class="span4"><strong>Store Added:</strong> <?php echo date("M j, Y H:i A",strtotime($item['created_at'])); ?></div>
                            <div class="span2 first"><strong>Auto-clean:</strong> <?php echo ((int)$item['do_hourly_db_revert'] ? 'Yes' : 'No'); ?></div>
                        </div>
                        <p class="description"><?php echo $item['description']; ?></p>
                        <div class="row">
                            <!-- START DETAILS BOX -->
                            <div class="span4 panel details">
                                <h5>Configuration</h5>
                                <div class="control-group">
                                    <div class="controls">
                                   	<?php if(in_array($item['status'], array('closed'))): ?>
                                        <a href="#" class="btn btn-inverse extensions-button disabled"><i class="icon icon-white icon-cog"></i> Extensions</a>
                                    <?php else: ?>
                                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'extensions', 'store' => $item['domain']), 'default', true); ?>"
                                           class="btn btn-inverse extensions-button"><i class="icon icon-white icon-cog"></i> Extensions</a>
                                    <?php endif; ?>
                                    <?php if($item['status']=='closed'): ?>
                                        <a href="#" class="btn edit-button disabled"><i class="icon icon-pencil"></i> Edit Details</a>
                                    <?php else: ?>
                                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'edit', 'id' => $item['id']), 'default', true); ?>"
                                           class="btn edit-button"><i class="icon icon-pencil"></i> Edit Details</a>
                                    <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <!-- END DETAILS BOX -->

                            <!-- START DEPLOYMENT BOX -->
                            <div class="span4 panel deployment">
                                <h5>Deployment <span class="version">version <span class="badge badge-blue"><?php echo (int)$this->escape($item['revision_count'])?></span></span></h5>
                                <div class="control-group">
                                    <div class="controls">
                                        <a href="#"
                                           class="btn rollback-button<?php echo ((int)$item['revision_count'] > 1 ? '' : ' disabled'); ?>"
                                           data-comment="<?php echo $item['comment']; ?>"
                                           >
                                            <i class="icon icon-circle-arrow-left"></i> Rollback
                                        </a>
                                        <a href="#" class="btn commit-button<?php echo ((int)$item['revision_count'] > 0 ? '' : ' disabled'); ?>" ><i class="icon icon-ok-sign"></i> Commit</a>
                                        <a href="#" class="btn deploy-button<?php echo ((int)$item['revision_count'] > 1 ? '' : ' disabled'); ?>">Deploy <i class="icon icon-circle-arrow-right"></i> </a>
                                        <input type="hidden" class="storedomain" value="<?php echo $this->escape($item['domain']) ?>" />
                                    </div>
                                </div>
                            </div>
                            <!-- END DEPLOYMENT BOX -->

                            <!-- START PROBLEMS BOX -->
                            <div class="span3 panel">
                                <h5>Troubleshooting</h5>
                                <div class="control-group">
                                    <div class="controls">
                                        <a target="_blank" href="<?php echo $item['papertrail_syslog_hostname'] ? $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'papertrail', 'domain' => $this->escape($item['domain'])), 'default', true) : '#'; ?>" class="btn log-button <?php echo ($item['papertrail_syslog_hostname']) ?: 'disabled'?>"><i class="icon icon-info-sign"></i> Show Logs</a>
                                        <a target="_blank" href="https://rocketwebinc.zendesk.com/anonymous_requests/new?ticket[fields][21917916]=<?php echo $this->serverUrl().$this->url(array('module' => 'default', 'controller' => 'store', 'action' => $item['domain']), 'default', true); ?>&email=<?php echo $this->user->email; ?>" class="btn help-button"><i class="icon icon-question-sign"></i> Get Help</a>
                                    </div>
                                </div>
                            </div>
                            <!-- END PROBLEMS BOX -->
                        </div>

                    </div>
                </div>
                <?php endif; // end div#collapse ?>
            </div>
            <!-- END STORE -->
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <!-- END ACCORDION -->

    </div>
</div>
<!-- START STORES PAGE -->

<div id="commitModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Commit Your Changes</h3>
    </div>
    <div class="modal-body">
        <p>All your changes will be committed to the repository.</p>
        <p>
            Briefly explain what you have changed since the last commit:
            <br />
            <textarea id="commit_comment" name="commit_comment" placeholder="Add your comment here" ></textarea>
        </p>
        <input type="hidden" value="" id="commit-domain" name="commit-domain" />
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary commit-confirm">Commit Changes</button>
    </div>
</div>

<div id="close-store" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Delete Store</h3>
    </div>
    <div class="modal-body">
        <p>Do you really want to delete store<span class="close-store-name"></span>? There is no undo!</p>
    </div>
    <div class="modal-footer">
        <form method="post">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <input type="hidden" name="close" value="1" />
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

<div id="store-deployment" class="modal hide fade modal-deploy" tabindex="-1" role="dialog" aria-hidden="true">
    <form method="post">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="rollback">Rollback</h3>
            <h3 class="deploy">Deployment List</h3>
            <h3 class="commit">Manual Commit</h3>
        </div>
        <div class="modal-body">
            <p class="rollback">
                This will rollback<span class="rollback-name"></span>. Are you sure you want rollback these changes?
            </p>
            <div class="rollback alert">Note: any changes you may have made to code or in the Magento admin after the last commit will be lost.</div>
            <p class="commit">
                This will save state of all files added and edited using FTP in your store. You will have the ability to rollback the last commit you've made. Are you sure you want to continue?<br />
                <label>Your comment:</label>
                <textarea id="commit_comment" name="commit_comment" placeholder="Add your comment here"></textarea>
                <span class="help-block">Briefly explain what has been changed since the last commit.</span>
            </p>
            <div class="deploy">
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <div class="commit">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" value="commit" name="action" class="btn btn-primary">Commit</button>
            </div>
            <div class="rollback">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" value="rollback" name="action" class="btn btn-primary">Rollback</button>
            </div>
            <p class="deploy pull-left">
                Choose saved state of your store and download a zip file of all changes to upload to your live store.
            </p>
        </div>
    </form>
</div>

<?php echo $this->paginationControl($this->queue, 'Sliding', '_partials/paginationControl.phtml'); ?>
<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>
