<h1>Your stores</h1>

<p>
    <a
        href="<?php echo $this->url(array('controller'=>'queue', 'action' => 'add'))?>"
        class="btn btn-primary btn-large"><i class="icon-plus icon-white"></i>&nbsp;New Build</a>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Edition</th>
            <th>Version</th>
            <th>Sample Data</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->queue as $item): ?>
        <tr>
            <td><?php echo $item['instance_name']?></td>
            <?php switch($item['status']): 
            case 'ready':?>
                <td><span class="label label-success"><?php echo ucfirst($item['status']) ?></span> </td>
            <?php break; case 'pending':  ?>
                <td>
                    <!--
                    <div class="progress progress-info progress-striped active">
                        <div class="bar" style="width: 100%;">
                            <span class="label label-warning">In Queue</span>
                            <span class="label">
                                <?php echo $this->queueCounter[$item['id']]; ?>
                                minutes left
                            </span>
                        </div>
                    </div>-->
                    <div class="progress progress-striped active" style="margin-bottom:0px;margin-top:5px;">
                        <div class="bar" style="width: 100%;">
                            In Queue - <?php echo $this->queueCounter[$item['id']]; ?> minutes left
                        </div>
                    </div>
                </td>
            <?php break; case 'closed': ?>
                <td><span class="label label-important">Closed</span></td>
            <?php break; case 'installing': ?>
                <td><span class="label label-success">Installing..</span></td>
            <?php break; default: ?>
                <td><span class="label label-warning"></span></td>
            <?php endswitch; ?>
            <td><?php echo $item['edition']?></td>
            <td><?php echo $item['version']?></td>
            <td>
            <?php if($item['sample_data']): ?>
                <span class="label label-success">Yes</span>
            <?php else: ?>
                <span class="label label-important">No</span>
            <?php endif; ?>
            </td>
            <td>
            <?php if(in_array($item['status'], array('closed','pending','installing'))): ?>
                <a class="btn btn-success disabled"><i class="icon-eye-close icon-white"></i>&nbsp;Visit</a>
                <a class="btn btn-danger disabled"><i class="icon-trash icon-white"></i>&nbsp;Close</a>
            <?php else: ?>
                <a href="<?php echo $this->baseUrl('instance/'.$item['domain']); ?>" class="btn btn-success"><i class="icon-eye-open icon-white"></i>&nbsp;Visit</a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'edit', 'id' => $item['id']), 'default', true); ?>" class="btn btn-info"><i class="icon-pencil icon-white"></i>&nbsp;Edit</a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'queue', 'action' => 'close', 'domain' => $item['domain']), 'default', true); ?>" class="btn btn-danger"><i class="icon-trash icon-white"></i>&nbsp;Close</a>
            <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->queue, 'Sliding', '_partials/paginationControl.phtml'); ?>