<div class="row">
    <div class="span12 user-details">
        <h1>Details Account</h1>
        <div class="form-box">
            <div class="box">


                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>User Details</legend>
                    <div class="row">
                        <dl class="dl-horizontal">
                            <dt>Username</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getLogin()); ?></dd>
                            <dt>Email</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getEmail()); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Name</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getFirstname()); ?> <?php echo $this->EmptyEscape($this->user->getLastname()); ?></dd>
                            <dt>Street</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getStreet()); ?></dd>
                            <dt>Postal code</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getPostalCode()); ?></dd>
                            <dt>City</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getCity()); ?></dd>
                            <dt>State</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getState()); ?></dd>
                            <dt>Country</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getCountry()); ?></dd>
                            <dt>Server</dt>
                            <dd><?php echo $this->EmptyEscape($this->server->getName()); ?></dd>
                            <dt>Group</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getGroup()); ?></dd>
                            <dt>Added date</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getAddedDate()); ?></dd>
                            <dt>Status</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getStatus()); ?></dd>
                            <dt>Plan</dt>
                            <dd><?php echo $this->EmptyEscape($this->plan->getName()); ?></dd>
                            <dt>Plan active to</dt>
                            <dd><?php echo $this->EmptyEscape($this->user->getPlanActiveTo()); ?></dd>
                            <?php if ($this->user->getHasSystemAccount()): ?>
                                <dt>System account name</dt>
                                <dd><?php echo $this->EmptyEscape($this->user->getSystemAccountName()); ?></dd>
                            <?php endif; ?>
                        </dl>
                    </div>

                </fieldset>

                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Coupons</legend>
                    <?php if ($this->coupon->getCode()): ?>
                        <h4><?php echo $this->EmptyEscape($this->coupon->getCode()); ?></h4>
                        <div class="row">
                            <dl class="dl-horizontal">
                                <dt>Used date</dt>
                                <dd><?php echo $this->EmptyEscape($this->coupon->getUsedDate()); ?></dd>
                                <dt>Plan</dt>
                                <dd><?php echo $this->EmptyEscape($this->plans[$this->coupon->getPlanId()]); ?></dd>
                                <dt>Duration</dt>
                                <dd><?php echo $this->EmptyEscape($this->coupon->getDuration()); ?></dd>
                                <dt>Active to</dt>
                                <dd><?php echo $this->EmptyEscape($this->coupon->getActiveTo()); ?></dd>
                            </dl>
                        </div>
                    <?php else: ?>
                        <div class="row">
                            <div class="span4">User has not used any coupons.</div>
                        </div>
                    <?php endif; ?>
                </fieldset>

                <div class="tab-stripe"></div>
                <fieldset>
                    <legend>Payments</legend>
                    <?php if($this->payments): ?>
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Date</th>
                                <th>Billing address</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->payments as $payment): ?>
                            <?php
                                $types = array(
                                    'subscription' => array('label' => 'Plan', 'class' => 'label-success'),
                                    'extension' => array('label' => 'Extension', 'class' => 'label-info'),
                                    'additional-stores' => array('label' => 'Additional Stores', 'class' => 'label-warning')
                                );
                            ?>
                            <tr>
                                <td><?php echo $payment->getId(); ?></td>
                                <td>
                                    <span class="label <?php echo $types[$payment->getTransactionType()]['class']; ?>"><?php echo $types[$payment->getTransactionType()]['label']; ?></span>
                                    <?php echo $payment->getTransactionName(); ?>
                                </td>
                                <td>$<?php echo $payment->getPrice(); ?></td>
                                <td><?php echo $payment->getDate(); ?></td>
                                <td>
                                    <?php echo $payment->getFirstName(), ' ', $payment->getLastName(); ?>
                                    <br />
                                    <?php echo $payment->getStreet(), ', ', $payment->getPostalCode(), ' ', $payment->getCity(); ?>
                                    <br />
                                    <?php echo $payment->getState(), ' ', $payment->getCountry(); ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php else: ?>
                    <h4>User has not made any payments.</h4>
                    <?php endif; ?>
                </fieldset>
            </div>
        </div>
    </div>
</div>