<div class="row">
    <div class="span12">
        <form
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>"
            id="<?php echo $this->form->getAttrib('id') ?>">
            
            <h1>Edit Account</h1>
            <fieldset>
                <div class="row">
                    <div class="span4">
                        <?php echo $this->form->firstname; ?>
                    </div>
                    <div class="span4">
                        <?php echo $this->form->lastname; ?>
                    </div>
                    <div class="span4">
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span4">
                        <?php echo $this->form->password; ?>
                    </div>
                    <div class="span4">
                        <?php echo $this->form->password_repeat; ?>
                    </div>
                    <div class="span4">
                        <?php echo $this->form->server_id; ?>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-inverse pull-right">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
                </button>
                <small class="pull-right"><a href="<?php echo $this->url(array('module' => 'default',
                        'controller'=>'user',
                        'action'=>'list',
                        ),'default',true); ?>" class="secondary" style="margin-right: 12px">View list</a> </small>
            </div>
        </form>
    </div>
</div>
