<div class="row">
    <div class="span8 offset2">
        <form
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>"
            id="<?php echo $this->form->getAttrib('id') ?>">
            <div class="modal-header">
                <h3>Edit Account</h3>
            </div>
            <div class="modal-body">
                <table>
                    <tbody>
                    <tr>
                        <td class="split-columns">
                            
                        </td>
                        <td>
                            <?php echo $this->form->email; ?>
                            <?php echo $this->form->firstname; ?>
                            <?php echo $this->form->lastname; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <small><a href="<?php echo $this->url(array('module' => 'default',
                        'controller'=>'user',
                        'action'=>'list',
                        ),'default',true); ?>" class="secondary">View list</a> </small>
                <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-primary">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
                </button>
            </div>
        </form>
    </div>
</div>