<h1>Users</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Status</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Stores</th>
            <th>Server</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->users as $user): ?>
        <tr>
            <td><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'detail', 'id' => $user['id'])); ?>"><?php echo $user['login']; ?></a></td>
            <td><?php echo $user['status']; ?></td>
            <td><?php echo $user['firstname']; ?></td>
            <td><?php echo $user['lastname']; ?></td>
            <td><?php echo $user['stores'] ?></td>
            <td><?php echo $user['server_label']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('module' => 'default', 
                    'controller' => 'user',
                    'action' => 'edit',
                    'id' => $user['id'])); ?>" class="btn btn-success"><i class="icon-white icon-pencil"></i>&nbsp;Edit</a>
            <?php if($user['status']=='deleted' || $user['group']=='admin'): ?>
                <a class="btn btn-danger disabled"><i class="icon-white icon-trash"></i>&nbsp;Delete</a>
            <?php else: ?>
                    <a href="#user-deletion" role="button" class="btn btn-danger user-remove" data-toggle="modal" data-user-id="<?php echo $user['id']; ?>"><i class="icon-white icon-trash"></i>&nbsp;Remove</a>
            <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->users, 'Sliding', '_partials/paginationControl.phtml'); ?>

<div id="user-deletion" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Delete User</h3>
    </div>
    <div class="modal-body">
        <p>Do you really want to delete user "<b></b>"</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Cancel</a>
        <form method="post" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'remove'), 'default', true); ?>">
            <input type="hidden" name="confirm" value="1" />
            <input type="hidden" name="id" value="" />
            <button class="btn btn-primary" type="submit">Remove</button>
        </form>
    </div>
</div>