<h1>Users</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Status</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Stores</th>
            <th>Server</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->users as $user): ?>
        <tr>
            <td><?php echo $user['login']; ?></td>
            <td><?php echo $user['status']; ?></td>
            <td><?php echo $user['firstname']; ?></td>
            <td><?php echo $user['lastname']; ?></td>
            <td><?php echo $user['instances'] ?></td>
            <td><?php echo $user['server_label']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('module' => 'default', 
                    'controller' => 'user',
                    'action' => 'edit',
                    'id' => $user['id'])); ?>" class="btn btn-success"><i class="icon-white icon-pencil"></i>&nbsp;Edit</a>
            <?php if($user['status']=='inactive' || $user['group']=='admin'): ?>
                <a class="btn btn-danger disabled"><i class="icon-white icon-trash"></i>&nbsp;Remove</a>
            <?php else: ?>
                <a href="<?php echo $this->url(array('module' => 'default', 
                    'controller' => 'user',
                    'action' => 'remove',
                    'id' => $user['id'])); ?>" class="btn btn-danger"><i class="icon-white icon-trash"></i>&nbsp;Remove</a>
            <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->users, 'Sliding', '_partials/paginationControl.phtml'); ?>