<div class="row">
    <div class="span4">&nbsp;</div>
    <div class="span8">
        <form action="<?php echo $this->form->getAction() ?>"
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            id="<?php echo $this->form->getId() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <div class="modal-header">
                <h3>Login</h3>
            </div>
            <div class="modal-body">
                <fieldset>
                    <?php echo $this->form->login; ?>
                    <?php echo $this->form->password; ?>
                </fieldset>
            </div>
            <div class="modal-footer">
                <small><a href="#" class="secondary">Forgot
                        password?</a> </small>
                <?php echo $this->form->submit; ?>
            </div>
        </form>
    </div>
</div>