<?php if ($this->useCoupons): ?>
<div class="alert alert-block">
  <a class="close" data-dismiss="alert">×</a>
  <h4 class="alert-heading">Warning!</h4>
  For now we are in beta test mode. We are accepting new registrations only with coupon code. We will be open on all new registrations soon.
</div>
<?php endif; ?>

<div class="row">
    <div class="span12">
        <form
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <legend>
                <h1>Create Account</h1>
            </legend>
            <fieldset class="margins">
                <h4>Account details</h4>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->login; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->password; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->password_repeat; ?>
                    </div>
                    <div class="span3">
                        
                    </div>
                </div>
            </fieldset>
            <fieldset class="margins">
                <h4>Personal details</h4>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->firstname; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->lastname; ?>
                    </div>
                </div>
            </fieldset>
            <fieldset class="margins">
                <h4>Extra</h4>
                <div class="row">
                    <div class="span3">
                        <?php echo $this->form->coupon; ?>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-inverse pull-right">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
                </button>
            </div>
        </form>
    </div>
</div>