<?php if ($this->useCoupons): ?>
<div class="alert alert-block">
  <a class="close" data-dismiss="alert">×</a>
  <h4 class="alert-heading">Warning!</h4>
  For now we are in beta test mode. We are accepting new registrations only with coupon code. We will be open on all new registrations soon.
</div>
<?php endif; ?>

<div class="row">
    <div class="span8 offset2">
        <form
            enctype="<?php echo $this->form->getEnctype() ?>"
            method="<?php echo $this->form->getMethod() ?>"
            class="<?php echo $this->form->getAttrib('class') ?>">
            <div class="modal-header">
                <h3>Create Account</h3>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tbody>
                    <tr>
                        <td class="split-columns">
                            <?php echo $this->form->login; ?>
                            <?php echo $this->form->password; ?>
                            <?php echo $this->form->password_repeat; ?>
                        </td>
                        <td>
                            <?php echo $this->form->email; ?>
                            <?php echo $this->form->firstname; ?>
                            <?php echo $this->form->lastname; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div id="coupon-holder">
                     <?php echo $this->form->coupon; ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" name="<?php echo $this->form->submit->getName(); ?>" id="<?php echo $this->form->submit->getId() ?>" class="btn btn-primary">
                    <i class="icon-white icon-ok"></i>&nbsp;<?php echo $this->form->submit->getLabel(); ?>
                </button>
                <button type="reset" name="<?php echo $this->form->reset->getName(); ?>" id="<?php echo $this->form->reset->getId() ?>" class="btn">
                    <i class="icon-repeat"></i>&nbsp;<?php echo $this->form->reset->getLabel(); ?>
                </button>
            </div>
        </form>
    </div>
</div>