<div class="row">
    <div class="span12">
        <h1>Reset Password</h1>
        <div class="form-box">
        	<div class="box">
        		<form method="post" class="form-stacked">
        		    <div class="tab-stripe"></div>
        		    <fieldset>
        		        <legend></legend>
        		        <div class="row">
        		            <div class="span12">
                    		    <label>
                    		        Please fill in your email address below and we will send you a message containing a link to reset your password.
                    		    </label>
        		                <?php echo $this->form->email; ?>
        		            </div>
        		        </div>
        		    </fieldset>
        		    <div class="form-actions">
        		        <div class="pull-right"><?php echo $this->form->submit; ?></div>
        		    </div>
        		</form>
        	</div>
        </div>
    </div>
</div>