<div class="row">
    <div class="span12">
        <form method="post" class="form-stacked">
            <legend>
                <h2>Reset Password</h2>
            </legend>
            <label>
                Fill inputs bellow and we will send you link to page where you will set your new password.
            </label>
            <fieldset>
                <div class="row">
                    <div class="span12">
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <div class="pull-right"><?php echo $this->form->submit; ?></div>
            </div>
        </form>
    </div>
</div>