<div class="row">
    <div class="span12">
        <div class="form-box">
        	<div class="box">
        		<form method="post" class="form-stacked">
                    <div class="tab-stripe"></div>
        		    <fieldset>
                        <legend>Set your new password here:</legend>
        		        <div class="row">
        		            <div class="span6">
        		                <?php echo $this->form->password; ?>
        		            </div>
        		            <div class="span6">
        		                <?php echo $this->form->password_repeat; ?>
        		            </div>
        		        </div>
        		    </fieldset>
        		    <div class="form-actions">
        		        <div class="pull-right"><?php echo $this->form->submit; ?></div>
        		    </div>
        		</form>
        	</div>
        </div>
    </div>
</div>