<h2>Set your new password here:</h2>
<div class="row">
    <div class="span4 well">
        <div class="span3 margin-reset-password">
            <form method="post">
                <?php echo $this->form->password; ?>                         
                <?php echo $this->form->password_repeat; ?>
                <hr />
                <?php echo $this->form->submit; ?>
            </form>
        </div>
    </div>
</div>