<div class="row">
    <div class="span12">
        <form method="post" class="form-stacked">
            <legend>
                <h1>Set your new password here:</h1>
            </legend>
            <fieldset>
                <div class="row">
                    <div class="span6">
                        <?php echo $this->form->password; ?>
                    </div>
                    <div class="span6">
                        <?php echo $this->form->password_repeat; ?>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <div class="pull-right"><?php echo $this->form->submit; ?></div>
            </div>
        </form>
    </div>
</div>