<?php
$this->headScript()->appendFile($this->baseUrl('public/js/lightbox.js'));
$this->headLink()->appendStylesheet($this->baseUrl('public/css/lightbox.css'));
?>
<div class="row">
    <div class="pull-left span6">
        <h1 class="page-title">Supported Extensions</h1>
    </div>
    <div class="pull-right">
        <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add new extension</a>
    </div>
</div>

<table class="table table-bordered table-striped admin-extensions">
    <thead>
        <tr>
            <th>Title</th>
            <th>Edition</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->extensions as $extension): ?>
        <tr>
            <td>
                <div class="media">
                    <?php if($extension['item']->getLogo()): ?>
                        <img class="pull-left media-object logo" src="<?php echo $this->ImagePath($extension['item']->getLogo(), 'extension/logo', false, true); ?>" />
                    <?php endif; ?>
                    <div class="media-body">
                        <h4 class="media-heading display-inline"><?php echo $extension['item']->getName(); ?></h4>
                        <?php if($extension['item']->getVersion()): ?>
                        <p class="display-inline">( <?php echo $extension['item']->getVersion(); ?> )</p>
                        <?php endif; ?>
                        <p><?php echo $extension['item']->getDescription(); ?></p>
                    </div>
                </div>
            </td>
            <td>
                <?php
                $supported_versions = '';
                $supported_versions .= (($version = $extension['item']->getFromVersion()) ? 'From  '.$version : '');
                $supported_versions .= (($version = $extension['item']->getToVersion()) ? ' to '.$version : '');
                if(!$supported_versions) {
                    $supported_versions = 'N.A.';
                }
                ?>
                <a href="#" 
                   class="label label-success"
                   rel="tooltip"
                   data-placement="top"
                   title="<?php echo $supported_versions; ?>">
                <?php echo $extension['item']->getEdition(); ?></a>
            </td>
            <td><?php echo $extension['item']->getPrice(); ?></td>
            <td class="nowrap">
                <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'edit', 'id' => $extension['item']->getId()), 'default', true); ?>" class="btn btn-success"><i class="icon-pencil icon-white"></i> Edit</a>
                <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'delete', 'id' => $extension['item']->getId()), 'default', true); ?>" class="btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                <a href="#" class="btn show-screenshots"><i class="icon-camera"></i></a>
                <div class="screenshots-container">
                    <?php foreach($extension['screenshots'] as $key => $screenshot): ?>
                        <a href="<?php echo $this->ImagePath($screenshot->getImage(), 'extension/screenshots', false); ?>" rel="lightbox[ext<?php echo $extension['item']->getId(); ?>]" title="<?php echo $extension['item']->getName(), ' ', $key+1; ?>#"><?php echo $extension['item']->getName(), ' ', $key+1; ?>#</a>
                    <?php endforeach; ?>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>