<div class="row">
    <div class="pull-left span6">
        <h1 class="page-title">Supported Extensions</h1>
    </div>
    
    <div class="pull-right">
        <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'add'), 'default', true); ?>" class="btn btn-blue btn-large"><i class="icon-plus icon-white"></i> Add new extension</a>
    </div>
    <div class="pull-right" >
        <form method="<?php $this->form->getMethod(); ?>" id="extension-filter-form">
            <?php echo $this->form->getElement('edition') ?>
        </form>
    </div>
</div>

<table class="table table-bordered table-striped admin-extensions">
    <thead>
        <tr>
            <th>Title</th>
            <th>Edition</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->extensions as $extension): ?>
        <tr>
            <td>
                <div class="media">
                    <?php if($extension['logo']): ?>
                        <?php echo $this->Thumbnail($extension['logo'], null, 110, array('class' => 'pull-left media-object logo', 'alt' => $extension['logo']), $this->ImagePath($extension['logo'], 'extension/logo', false, false)); ?>
                    <?php endif; ?>
                    <div class="media-body">
                        <h4 class="media-heading display-inline"><?php echo $extension['name']; ?></h4>
                        <?php if($extension['version']): ?>
                        <p class="display-inline">( <?php echo $extension['version']; ?> )</p>
                        <?php endif; ?>
                        <p><?php echo $extension['description']; ?></p>
                    </div>
                </div>
            </td>
            <td>
                <?php
                $supported_versions = '';
                $supported_versions .= (($version = $extension['from_version']) ? 'From  '.$version : '');
                $supported_versions .= (($version = $extension['to_version']) ? ' to '.$version : '');
                if(!$supported_versions) {
                    $supported_versions = 'N.A.';
                }
                ?>
                <a href="#" 
                   class="label label-success"
                   rel="tooltip"
                   data-placement="top"
                   title="<?php echo $supported_versions; ?>">
                <?php echo $extension['edition']; ?></a>
            </td>
            <td><?php echo $extension['price']; ?></td>
            <td class="nowrap">
                <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'edit', 'id' => $extension['id']), 'default', true); ?>" class="btn btn-success"><i class="icon-pencil icon-white"></i> Edit</a>
                <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'delete', 'id' => $extension['id']), 'default', true); ?>" class="btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->extensions, 'Sliding', '_partials/paginationControl.phtml'); ?>