<?php
    $this->headScript()->appendFile($this->baseUrl('public/js/jquery.isotope.min.js'));
    $page_type = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    // because we have extensions and extension controller
    // change extensions ( guest access ) to frontend
    $page_type = ('extensions' == $page_type ? 'frontend' : $page_type);
?>
<div class="row">
    <div class="span12">
        <h1 class="pull-left">
    <?php if('queue' == $page_type): ?>
        '<?php echo $this->store_name; ?>' Extensions
    <?php elseif('frontend' == $page_type): ?>
        All Available Extensions
    <?php else: ?>
        Manage Extensions
    <?php endif; ?>
        </h1>
        <?php if('extension' == $page_type): ?>
        <div class="pull-right btn-add-ext">
            <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'add'), 'default', true); ?>" class="btn btn-blue btn-large"><i class="icon-plus icon-white"></i> Add new extension</a>
        </div>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <div class="span12">
        <div class="form-box">
            <div id="extensions" class="box">
                <div class="tab-stripe"></div>
                <div class="mt_filters">
                    <section id="options" class="clearfix">
                        <div class="btn-toolbar pull-left">
                            
                            <div class="btn-group" data-title="Price filter">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Price filter <span class="caret"></span></a>
                                <ul class="dropdown-menu option-set" data-option-key="price" style="width:100%">
                                    <li><a class="btn-all" tabindex="-1" href="#" data-option-value="*">All</a></li>
                                    <li class="divider"></li>
                                    <li><a class="btn-goldd" tabindex="-1" href="#" data-option-value=".premium">Premium</a></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".free">Free</a></li>
                                </ul>
                            </div>
                            
                            <div class="btn-group" data-title="Categories">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Categories <span class="caret"></span></a>
                                <ul class="dropdown-menu option-set" data-option-key="category">
                                    <li><a class="btn-all" tabindex="-1" href="#" data-option-value="*">All</a></li>
                                    <li class="divider"></li>
                                    <?php foreach($this->categories as $category): ?>
                                    <li><a tabindex="-1" href="#" data-option-value="<?php echo $category->getId(); ?>"><?php echo $category->getName(); ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <?php if('queue' == $page_type): ?>
                            <div class="btn-group" data-title="My store">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">My store <span class="caret"></span></a>
                                <ul class="dropdown-menu option-set" data-option-key="install">
                                    <li><a class="btn-all" tabindex="-1" href="#" data-option-value="*">All</a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".installed">Installed</a></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".notInstalled">Not installed</a></li>
                                </ul>
                            </div>
                            <?php endif; ?>
                            <?php if('extension' == $page_type): ?>
                            <div class="btn-group" data-title="Edition">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Edition <span class="caret"></span></a>
                                <ul class="dropdown-menu option-set" data-option-key="edition">
                                    <li><a class="btn-all" tabindex="-1" href="#" data-option-value="*">All</a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".ce">CE</a></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".pe">PE</a></li>
                                    <li><a tabindex="-1" href="#" data-option-value=".ee">EE</a></li>
                                </ul>
                            </div>
                            <div class="btn-group" data-title="Sort by">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Sort by <span class="caret"></span></a>
                                <ul class="dropdown-menu option-set" data-option-key="sort">
                                    <li><a class="btn-all" tabindex="-1" href="#" data-option-value="*">None</a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1" href="#" data-option-value="id-asc">Id: asc</a></li>
                                    <li><a tabindex="-1" href="#" data-option-value="id-desc">Id: desc</a></li>
                                </ul>
                            </div>
                            <?php endif; ?>
                            <!--<div class="btn-group option-set" data-toggle="buttons-radio" data-option-key="filter">
                                <button class="btn btn-small btn-all" data-option-value="*">All</button>
                                <button class="btn btn-small btn-gold" data-option-value=".premium">Premium</button>
                                <button class="btn btn-small btn-inverse" data-option-value=".free">Free</button>
                            </div>
                            <div class="btn-group option-set option-center" data-toggle="buttons-radio" data-option-key="filter">
                                <button class="btn btn-small btn-all" data-option-value="*">All</button>
                                <?php foreach($this->categories as $category): ?>
                                <button class="btn btn-small" data-option-value=".<?php echo $category->getClass(); ?>"><?php echo $category->getName(); ?></button>
                                <?php endforeach; ?>
                            </div>
                            <div class="btn-group option-set" data-toggle="buttons-radio" data-option-key="filter">
                                <button class="btn btn-small btn-all" data-option-value="*">All</button>
                                <button class="btn btn-small" data-option-value=".installed">Installed</button>
                                <button class="btn btn-small" data-option-value=".notInstalled">Not Installed</button>
                            </div>-->
                            <div class="btn-group extension-counter" style="margin-top: 4px;">
                                <div class="label label-info hide">Loading Extensions...</div>
                                <div class="label label-important"><span><?php echo $this->extensions_counter; ?></span> Extension(s)</div>
                            </div>
                        </div>
                        <form class="pull-right search-as-you-type">
                            <input class="search-as-you-type-input" type="text" placeholder="Search">
                        </form>
                    </section>
                </div>
                <div class="extensions_well">
                    <div id="container" class="clickable clearfix" data-form-action="<?php echo $this->baseUrl() ?>">
                    <?php echo $this->partial('extension/tiles.phtml', array('extensions' => $this->extensions, 'store_domain' => $this->store_domain, 'categories' => $this->categories)); ?>
                    </div>
                    <div class="load-more">
                        <a class="btn btn-large disabled hidden">LOADING MORE EXTENSIONS...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if('extension' == $page_type):
    $this->headScript()->appendFile($this->baseUrl('public/js/manage-extensions.js'));
?>
<div class="modal hide fade version-list-modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3></h3>
    </div>
    <div class="modal-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Version</th>
                    <th>Files</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <form action="<?php echo $this->url(array('controller' => 'extension', 'action' => 'add-version-to-extension'), 'default', true); ?>" method="POST" class="form form-horizontal">
            <input name="id" type="hidden" />
            <div class="control-group">
                <div class="control-label">Fill version number to create new release based on the most recent one.</div>
                <div class="controls">
                    <div class="input-append">
                        <input name="version" class="span1" type="text" placeholder="version" />
                        <button class="btn">Get latest</button>
                    </div>
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            Add release
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Add release</a><input type="submit" class="hide" /></li>
                            <li><a href="#">Add and edit release</a><input type="submit" name="edit_release" value="1" class="hide" /></li>
                        </ul>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>

<!-- START SCREENSHOTS CAROUSEL -->
<div id="screenshots">
    <div id="screenshotModal" class="modal fade">
        <div id="screenshotCarousel" class="carousel">
            <div class="carousel-inner">
            </div>
            <!-- Carousel nav -->
            <a class="carousel-control left" href="#screenshotCarousel" data-slide="prev"><span>&lsaquo;</span></a>
            <a class="carousel-control right" href="#screenshotCarousel" data-slide="next"><span>&rsaquo;</span></a>
        </div>
    </div>
</div>
<!-- END SCREENSHOTS CAROUSEL -->

<?php 
    $data = <<<EOT

EOT;
    echo $this->partial('_partials/helpContext.phtml', array('data' => $data)); 
?>
