<?php
    $page_type = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    // because we have extensions and extension controller
    // change extensions ( guest access ) to frontend
    $page_type = ('extensions' == $page_type ? 'frontend' : $page_type);
    // new release synchroznicer
    if('extension' == $page_type) {
        $sync = new Application_Model_ExtensionVersionSynchronizer();
    }
?>
<?php foreach($this->extensions as $extension): ?>
<div class="element <?php echo $extension['category_class']; ?> <?php echo strtolower($extension['edition']).' ', ((float)$extension['price'] ? 'premium' : 'free'), ('queue' == $page_type ? ($extension['status'] == 'ready' ? ' installed' : ' notInstalled') : ''); ?>"
<?php if('frontend' != $page_type): ?>
    id="extension_<?php echo $extension['id']; ?>"
<?php endif; ?>
<?php if('queue' == $page_type): ?>
    data-store-extension-id="<?php echo $extension['store_extension_id']; ?>"
<?php endif; ?>
>
<?php if('extension' == $page_type && is_string($sync->checkVersion($extension['extension_key'], $extension['version']))): ?>
    <div class="new-release"><i class="icon-retweet"></i></div>
<?php endif; ?>
    <div class="wrapper">
        <!-- removing this one for now until some workaround is found -->
            <!--<div class="hover_inner_shadow"></div>-->

        <?php if((float)$extension['price']): ?>
            <?php if('queue' == $page_type AND $extension['status'] == 'ready'): ?>
            <div class="ribbon"><img src="<?php echo $this->baseUrl('/public/img/extensions/ribbon_premium_installed.png'); ?>" alt="premium" /></div>
            <?php else: ?>
            <div class="ribbon"><img src="<?php echo $this->baseUrl('/public/img/extensions/ribbon_premium.png'); ?>" alt="premium" /></div>
            <?php endif; ?>
        <?php else: ?>
            <?php if('queue' == $page_type AND $extension['status'] == 'ready'): ?>
            <div class="ribbon"><img src="<?php echo $this->baseUrl('/public/img/extensions/ribbon_free_installed.png'); ?>" alt="free" /></div>
            <?php else: ?>
            <div class="ribbon"><img src="<?php echo $this->baseUrl('/public/img/extensions/ribbon_free.png'); ?>" alt="free" /></div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if($extension['logo']): ?>
        <div class="icon big">
            <?php echo $this->Thumbnail($extension['logo'], null, 110, array('alt' => $extension['logo']), $this->ImagePath($extension['logo'], 'extension/logo', false, false)); ?>
        </div>
        <div class="icon small">
            <?php echo $this->Thumbnail($extension['logo'], null, 38, array('alt' => $extension['logo']), $this->ImagePath($extension['logo'], 'extension/logo', false, false)); ?>
        </div>
        <?php else: ?>
            <?php if($extension['category_logo']): ?>
                <div class="icon big">
                    <?php echo $this->Thumbnail($extension['category_logo'], null, 110, array('alt' => $extension['category_logo']), '/public/img/extensions/'); ?>
                </div>
                <div class="icon small">
                    <?php echo $this->Thumbnail($extension['category_logo'], null, 38, array('alt' => $extension['category_logo']), '/public/img/extensions/'); ?>
                </div>
            <?php else: ?>
                <?php $random_logo = $this->categories[mt_rand(0,2)]->getLogo(); ?>
                <div class="icon big">
                    <?php echo $this->Thumbnail($random_logo, null, 110, array('alt' => $random_logo), '/public/img/extensions/'); ?>
                </div>
                <div class="icon small">
                    <?php echo $this->Thumbnail($random_logo, null, 38, array('alt' => $random_logo), '/public/img/extensions/'); ?>
                </div>
            <?php endif; ?>
            
        <?php endif; ?>

        <div class="info">
            <div class="info-main">
                <h5><?php echo $extension['name']; ?></h5>
                <p class="author">by <?php echo $extension['author']; ?></p>
            </div>
            <?php if((float)$extension['price']): ?>
            <p class="extension-price pull-right">$<?php printf("%d", $extension['price']); ?></p>
            <?php endif; ?>
            <p class="extension-version">Version: <?php echo $extension['version']; ?><?php echo 'extension' == $page_type ? ' ('.$extension['edition'].')' : ''; ?></p>
        </div>

        <div class="extras hidden">
            <p class="description"><?php echo wordwrap($extension['description'], 45, ' ', true); ?></p>
            <?php if(
                    (isset($extension['screenshots']) AND count($extension['screenshots'])) ||
                    (strlen($extension['extension_detail'])) ||
                    (strlen($extension['extension_documentation']))
                    ): ?>
            <div class="btn-group">
              <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                Screenshots &amp; More
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <?php if(isset($extension['screenshots']) AND count($extension['screenshots'])): ?>
                <li>
                    <a href="#" class="btn-screenshots">View Screenshots</a>
                    <!-- START EXTENSION'S SCREENSHOTS -->
                    <!-- I've implemented them as a hidden list. This way they can be retrieved for individual extensions -->
                    <ul class="screenshots hidden">
                    <?php foreach($extension['screenshots'] as $key => $screenshot): ?>
                        <li data-id="<?php echo $extension['name'].' #'.++$key; ?>"><?php echo $this->ImagePath($screenshot, 'extension/screenshots', false, true); ?></li>
                    <?php endforeach; ?>
                    </ul>
                    <!-- END EXTENSION'S SCREENSHOTS -->
                </li>
                <?php endif; ?>

                <?php if (!strlen($extension['extension_detail'])): ?>
                <li><a href="<?php echo $extension['extension_detail']; ?>" class="" target="_blank">View Details</a></li>
                <?php endif; ?>

                <?php if (strlen($extension['extension_documentation'])): ?>
                <li><a href="<?php echo $extension['extension_documentation']; ?>" class="" target="_blank">Read Documentation</a></li>
                <?php endif; ?>
              </ul>
            </div>
            <?php endif; ?>
        <?php if('queue' == $page_type): ?>
            <?php if($extension['status']): ?>
                <?php if($extension['status'] == 'pending'): ?>
                <span class="label update-status label-info pull-right">Pending</span>
                <?php elseif($extension['status'] == 'processing'): ?>
                <span class="label update-status label-important pull-right">Installing</span>
                <?php endif; ?>
            <?php endif; ?>
            <?php if(!$extension['status']): ?>
                <a href="#" class="btn btn-danger btn-mini pull-right install" data-install-extension="<?php echo $extension['id']; ?>"><i class="icon icon-white icon-cog"></i> Install</a>
            <?php elseif((float)$extension['price'] AND $extension['status'] == 'ready' AND !$extension['braintree_transaction_id']): ?>
                <form method="post" action="<?php echo $this->url(array('controller' => 'payment', 'action' => 'payment'), 'default', true); ?>">
                    <input type="hidden" name="pay-for" value="extension" />
                    <input type="hidden" name="id" value="<?php echo $extension['id']; ?>" />
                    <input type="hidden" name="source" value="extension" />
                    <input type="hidden" name="domain" value="<?php echo $this->store_domain; ?>" />
                    <button type="submit" class="btn btn-success btn-mini pull-right buy"><i class="icon icon-white icon-shopping-cart"></i> Buy</button>
                </form>
            <?php endif; ?>
        <?php elseif('extension' == $page_type): ?>
            <a href="<?php echo $this->url(array('controller' => 'extension', 'action' => 'list-versions', 'id' => $extension['id']), 'default', true); ?>" class="btn btn-mini pull-right version-list" data-extension-id="<?php echo $extension['id']; ?>">View releases</a>
        <?php endif;?>
        </div>
    </div>
</div>
<?php endforeach; ?>